<a href="https://colab.research.google.com/github/S-IMPANA/Data_Analytics_Project/blob/main/Retail_Dataset_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**E-Commerce Data Analysis Project Online Retail Dataset Analysis**

In [ ]:
import numpy as np
import pandas as pd

# 📊 Dataset Information
**Dataset: Online Retail Dataset**

# 🎯 Project Tasks
**PART A: Initial Data Exploration**

**Task 1**: Load the dataset and display basic information about its structure.

In [ ]:
import kagglehub
path = kagglehub.dataset_download("vijayuv/onlineretail")

Using Colab cache for faster access to the 'onlineretail' dataset.


In [ ]:
df=pd.read_csv('/kaggle/input/onlineretail/OnlineRetail.csv',encoding='ISO-8859-1')

In [ ]:
df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[541909 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    541909 non-null  object 
 1   StockCode    541909 non-null  object 
 2   Description  540455 non-null  object 
 3   Quantity     541909 non-null  int64  
 4   InvoiceDate  541909 non-null  object 
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB


**Task 2:** Show the first 15 and last 15 records.

In [ ]:
df.head(15)

InvoiceNo StockCode                          Description  Quantity  \
0     536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1     536365     71053                  WHITE METAL LANTERN         6   
2     536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3     536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4     536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
5     536365     22752         SET 7 BABUSHKA NESTING BOXES         2   
6     536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6   
7     536366     22633               HAND WARMER UNION JACK         6   
8     536366     22632            HAND WARMER RED POLKA DOT         6   
9     536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32   
10    536367     22745           POPPY'S PLAYHOUSE BEDROOM          6   
11    536367     22748            POPPY'S PLAYHOUSE KITCHEN         6   
12    536367     22749    FELTCRAFT PRINCESS CHARLOTTE DOLL         8   
13    536367     22310              IVORY KNITTED MUG COSY          6   
14    536367     84969   BOX OF 6 ASSORTED COLOUR TEASPOONS         6   

       InvoiceDate  UnitPrice  CustomerID         Country  
0   12/1/2010 8:26       2.55     17850.0  United Kingdom  
1   12/1/2010 8:26       3.39     17850.0  United Kingdom  
2   12/1/2010 8:26       2.75     17850.0  United Kingdom  
3   12/1/2010 8:26       3.39     17850.0  United Kingdom  
4   12/1/2010 8:26       3.39     17850.0  United Kingdom  
5   12/1/2010 8:26       7.65     17850.0  United Kingdom  
6   12/1/2010 8:26       4.25     17850.0  United Kingdom  
7   12/1/2010 8:28       1.85     17850.0  United Kingdom  
8   12/1/2010 8:28       1.85     17850.0  United Kingdom  
9   12/1/2010 8:34       1.69     13047.0  United Kingdom  
10  12/1/2010 8:34       2.10     13047.0  United Kingdom  
11  12/1/2010 8:34       2.10     13047.0  United Kingdom  
12  12/1/2010 8:34       3.75     13047.0  United Kingdom  
13  12/1/2010 8:34       1.65     13047.0  United Kingdom  
14  12/1/2010 8:34       4.25     13047.0  United Kingdom

In [ ]:
df.tail(15)

InvoiceNo StockCode                      Description  Quantity  \
541894    581587     22631         CIRCUS PARADE LUNCH BOX         12   
541895    581587     22556   PLASTERS IN TIN CIRCUS PARADE         12   
541896    581587     22555        PLASTERS IN TIN STRONGMAN        12   
541897    581587     22728        ALARM CLOCK BAKELIKE PINK         4   
541898    581587     22727        ALARM CLOCK BAKELIKE RED          4   
541899    581587     22726       ALARM CLOCK BAKELIKE GREEN         4   
541900    581587     22730       ALARM CLOCK BAKELIKE IVORY         4   
541901    581587     22367  CHILDRENS APRON SPACEBOY DESIGN         8   
541902    581587     22629              SPACEBOY LUNCH BOX         12   
541903    581587     23256      CHILDRENS CUTLERY SPACEBOY          4   
541904    581587     22613      PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899     CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254    CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138    BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID Country  
541894  12/9/2011 12:50       1.95     12680.0  France  
541895  12/9/2011 12:50       1.65     12680.0  France  
541896  12/9/2011 12:50       1.65     12680.0  France  
541897  12/9/2011 12:50       3.75     12680.0  France  
541898  12/9/2011 12:50       3.75     12680.0  France  
541899  12/9/2011 12:50       3.75     12680.0  France  
541900  12/9/2011 12:50       3.75     12680.0  France  
541901  12/9/2011 12:50       1.95     12680.0  France  
541902  12/9/2011 12:50       1.95     12680.0  France  
541903  12/9/2011 12:50       4.15     12680.0  France  
541904  12/9/2011 12:50       0.85     12680.0  France  
541905  12/9/2011 12:50       2.10     12680.0  France  
541906  12/9/2011 12:50       4.15     12680.0  France  
541907  12/9/2011 12:50       4.15     12680.0  France  
541908  12/9/2011 12:50       4.95     12680.0  France

**Task 3:** Display a random sample of 20 transactions.

In [ ]:
df.sample(20)

InvoiceNo StockCode                          Description  Quantity  \
22681     538177     21448            12 DAISY PEGS IN WOOD BOX         1   
365000    568690     21080  SET/20 RED RETROSPOT PAPER NAPKINS          4   
225399    556671     23284        DOORMAT KEEP CALM AND COME IN         2   
491802    578074     23198       PANTRY MAGNETIC  SHOPPING LIST         4   
364136    568650     22961               JAM MAKING SET PRINTED        12   
519984    580214     23497         CLASSIC CHROME BICYCLE BELL         12   
51007     540604     22718                   CARD CAT AND TREE         12   
256756    559506     21901                 KEY FOB , BACK DOOR          1   
330272    565917     22792         FLUTED ANTIQUE CANDLE HOLDER        16   
191467    553369     22699     ROSES REGENCY TEACUP AND SAUCER          4   
152318    549586     22728            ALARM CLOCK BAKELIKE PINK         2   
468724    576539     22776        SWEETHEART 3 TIER CAKE STAND          1   
4255      536755    84870B                    BLUE GEISHA GIRL          1   
500008    578703     22563                  HAPPY STENCIL CRAFT         4   
251867    559055     21204          DAISIES  HONEYCOMB GARLAND          3   
166541    550939     22224               WHITE LOVEBIRD LANTERN         6   
25302     538366     21259          VICTORIAN SEWING BOX SMALL          6   
220680    556207    84596B   SMALL DOLLY MIX DESIGN ORANGE BOWL         8   
132458    547665     22839      3 TIER CAKE TIN GREEN AND CREAM         1   
536081    581218     23201                   JUMBO BAG ALPHABET        10   

             InvoiceDate  UnitPrice  CustomerID         Country  
22681    12/10/2010 9:51       3.36         NaN  United Kingdom  
365000   9/28/2011 14:43       0.85     16332.0  United Kingdom  
225399   6/13/2011 16:33       7.95     17841.0  United Kingdom  
491802  11/22/2011 16:06       1.45     17590.0  United Kingdom  
364136   9/28/2011 11:56       1.45     13505.0     Switzerland  
519984   12/2/2011 12:10       1.45     14092.0  United Kingdom  
51007    1/10/2011 11:38       0.42     15326.0  United Kingdom  
256756    7/8/2011 15:17       1.63         NaN  United Kingdom  
330272    9/7/2011 16:15       1.63         NaN  United Kingdom  
191467   5/16/2011 14:30       2.95     15044.0  United Kingdom  
152318   4/11/2011 10:00       8.29         NaN  United Kingdom  
468724  11/15/2011 12:43       9.95     13058.0  United Kingdom  
4255     12/2/2010 14:14       3.75         NaN  United Kingdom  
500008  11/25/2011 11:02       1.25     17385.0  United Kingdom  
251867    7/5/2011 17:09       1.63         NaN  United Kingdom  
166541   4/21/2011 15:25       2.95     16146.0  United Kingdom  
25302   12/12/2010 10:47       5.95     18109.0  United Kingdom  
220680    6/9/2011 13:50       0.42     17372.0  United Kingdom  
132458   3/24/2011 13:17      14.95     14256.0  United Kingdom  
536081    12/8/2011 9:23       2.08     14191.0  United Kingdom

Task 4: Find out how many rows and columns are in the dataset.

In [ ]:
df.shape

(541909, 8)

Task 5: List all column names.

In [ ]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

Task 6: Check the data type of each column.

In [ ]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    541909 non-null  object 
 1   StockCode    541909 non-null  object 
 2   Description  540455 non-null  object 
 3   Quantity     541909 non-null  int64  
 4   InvoiceDate  541909 non-null  object 
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB


**Task 7:** Get a statistical summary of all numerical columns.

In [ ]:
df.describe()

Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [ ]:
df.describe(include='all')

InvoiceNo StockCode                         Description       Quantity  \
count     541909    541909                              540455  541909.000000   
unique     25900      4070                                4223            NaN   
top       573585    85123A  WHITE HANGING HEART T-LIGHT HOLDER            NaN   
freq        1114      2313                                2369            NaN   
mean         NaN       NaN                                 NaN       9.552250   
std          NaN       NaN                                 NaN     218.081158   
min          NaN       NaN                                 NaN  -80995.000000   
25%          NaN       NaN                                 NaN       1.000000   
50%          NaN       NaN                                 NaN       3.000000   
75%          NaN       NaN                                 NaN      10.000000   
max          NaN       NaN                                 NaN   80995.000000   

             InvoiceDate      UnitPrice     CustomerID         Country  
count             541909  541909.000000  406829.000000          541909  
unique             23260            NaN            NaN              38  
top     10/31/2011 14:41            NaN            NaN  United Kingdom  
freq                1114            NaN            NaN          495478  
mean                 NaN       4.611114   15287.690570             NaN  
std                  NaN      96.759853    1713.600303             NaN  
min                  NaN  -11062.060000   12346.000000             NaN  
25%                  NaN       1.250000   13953.000000             NaN  
50%                  NaN       2.080000   15152.000000             NaN  
75%                  NaN       4.130000   16791.000000             NaN  
max                  NaN   38970.000000   18287.000000             NaN

In [ ]:
df.describe(include='object')

InvoiceNo StockCode                         Description  \
count     541909    541909                              540455   
unique     25900      4070                                4223   
top       573585    85123A  WHITE HANGING HEART T-LIGHT HOLDER   
freq        1114      2313                                2369   

             InvoiceDate         Country  
count             541909          541909  
unique             23260              38  
top     10/31/2011 14:41  United Kingdom  
freq                1114          495478

**PART B: Data Quality Assessment**

Task 8: Identify which columns have missing values and how many.

In [ ]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Task 9: Find out how many transactions have missing CustomerID.

In [ ]:
df['CustomerID'].isna().sum()

np.int64(135080)

Task 10: Check if there are any duplicate rows in the dataset.

In [ ]:
df.duplicated().sum()

np.int64(5268)

Task 11: Identify transactions where Quantity is less than or equal to zero.

In [ ]:
(df['Quantity']<=0).sum()

np.int64(10624)


Task 12: Find transactions where UnitPrice is zero or negative.

In [ ]:
(df['UnitPrice']<=0).sum()

np.int64(2517)

Task 13: Identify how many invoice numbers start with the letter 'C'.

In [ ]:
(df['InvoiceNo'].str[0]=='C').sum()

np.int64(9288)

Task 14: Check if the Description column has any leading or trailing spaces.

In [ ]:
df['Description'].str.startswith(' ').count()

np.int64(540455)

In [ ]:
df['Description'].str.endswith(' ').count()

np.int64(540455)

In [ ]:
df['Description'].str.startswith(' ').sum()

1271

In [ ]:
df['Description'].str.endswith(' ').sum()

112626

**PART C: Data Cleaning**

Task 15: Remove all rows where CustomerID is missing.

In [ ]:
df['CustomerID'].isna().sum()

np.int64(135080)

In [ ]:
df['CustomerID'].isna().any().sum()

np.int64(1)

In [ ]:
df=df.dropna(subset=['CustomerID'])

In [ ]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64


Task 16: For missing product descriptions, fill them with "Unknown Product".

In [ ]:
df['Description']=df['Description'].fillna('Unknown Product')

/tmp/ipython-input-3857982948.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Description']=df['Description'].fillna('Unknown Product')


In [ ]:
df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[406829 rows x 8 columns]

Task 17: Remove all duplicate transactions.

In [ ]:
df.duplicated().sum()

np.int64(5225)

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

Task 18: Remove transactions where Quantity is less than or equal to zero.

In [ ]:
df_clean1=df[df['Quantity']>=0]

In [ ]:
df_clean1

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[392732 rows x 8 columns]

In [ ]:
(df_clean1['Quantity']<=0).sum()

np.int64(0)

In [ ]:
df_clean1['Quantity'].unique()

array([    6,     8,     2,    32,     3,     4,    24,    12,    48,
          18,    20,    36,    80,    64,    10,   120,    96,    23,
           5,     1,    50,    40,   100,   192,   432,   144,   288,
          16,     9,   128,    25,    30,    28,     7,    72,   200,
         600,   480,    14,    11,    70,   252,    60,   216,   384,
          27,   108,    52,    75,   270,    42,   240,    90,   320,
          17,  1824,   204,    69,   160,  2880,  1400,    19,    39,
          56,    13,  1440,    15,   720,   156,   324,    41,   402,
         378,   150,   300,    22,    34,   408,   972,   208,  1008,
          26,  1000,  1488,   250,  1394,   400,   110,    37,    78,
          21,   272,    84,    47,  1728,    38,    53,    76,   576,
          29,  2400,   500,   180,   960,  1296,   147,   168,   256,
          54,    31,   860,  1010,  1356,  1284,   186,   114,   360,
        1930,  2000,  3114,  1300,   670,   176,   648,    62, 74215,
          89,    33,

Task 19: Remove transactions where UnitPrice is less than or equal to zero.

In [ ]:
df_clean2=df[df['UnitPrice']>=0]

In [ ]:
df_clean2

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[401604 rows x 8 columns]

In [ ]:
df_clean2['UnitPrice']

0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ... 
541904    0.85
541905    2.10
541906    4.15
541907    4.15
541908    4.95
Name: UnitPrice, Length: 401604, dtype: float64

In [ ]:
(df_clean2['UnitPrice']<=0).sum()

np.int64(40)

Task 20: Remove all cancelled transactions (invoices starting with 'C').

In [ ]:
df_clean3=df[df['InvoiceNo'].str[0]!='C']

In [ ]:
df_clean3

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[392732 rows x 8 columns]

In [ ]:
(df_clean3['InvoiceNo'].str[0]=='C').sum()

np.int64(0)

Task 21: Change the column name "Description" to "ProductName".

In [ ]:
df=df.rename(columns={'Description':'ProductName'})


Task 22: Ensure the InvoiceDate column is in proper date-time format.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    401604 non-null  object 
 1   StockCode    401604 non-null  object 
 2   ProductName  401604 non-null  object 
 3   Quantity     401604 non-null  int64  
 4   InvoiceDate  401604 non-null  object 
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      401604 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 27.6+ MB


In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [ ]:
df.dtypes

InvoiceNo              object
StockCode              object
ProductName            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

Task 23: Convert CustomerID to integer type

In [ ]:
df['CustomerID']=df['CustomerID'].astype(int)

In [ ]:
df.dtypes

InvoiceNo              object
StockCode              object
ProductName            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object


Task 24: Reset the index after all cleaning operations.

In [ ]:
df

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID         Country  
0      2010-12-01 08:26:00       2.55       17850  United Kingdom  
1      2010-12-01 08:26:00       3.39       17850  United Kingdom  
2      2010-12-01 08:26:00       2.75       17850  United Kingdom  
3      2010-12-01 08:26:00       3.39       17850  United Kingdom  
4      2010-12-01 08:26:00       3.39       17850  United Kingdom  
...                    ...        ...         ...             ...  
541904 2011-12-09 12:50:00       0.85       12680          France  
541905 2011-12-09 12:50:00       2.10       12680          France  
541906 2011-12-09 12:50:00       4.15       12680          France  
541907 2011-12-09 12:50:00       4.15       12680          France  
541908 2011-12-09 12:50:00       4.95       12680          France  

[401604 rows x 8 columns]

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df.dtypes

InvoiceNo              object
StockCode              object
ProductName            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID              int64
Country                object
dtype: object

**PART D: Feature Creation**


Task 25: Create a new column called "TotalPrice" that represents the total value of each transaction.

In [ ]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']


In [ ]:
df['TotalPrice']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...  
401599    10.20
401600    12.60
401601    16.60
401602    16.60
401603    14.85
Name: TotalPrice, Length: 401604, dtype: float64

Task 26: Extract the year from InvoiceDate and store it in a new column "Year".

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Year'] = df['InvoiceDate'].dt.year


In [ ]:
df['Year']

0         2010
1         2010
2         2010
3         2010
4         2010
          ... 
401599    2011
401600    2011
401601    2011
401602    2011
401603    2011
Name: Year, Length: 401604, dtype: int32

Task 27: Extract the month from InvoiceDate and store it in a new column "Month".

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Month'] = df['InvoiceDate'].dt.month


In [ ]:
df['Month']

0         12
1         12
2         12
3         12
4         12
          ..
401599    12
401600    12
401601    12
401602    12
401603    12
Name: Month, Length: 401604, dtype: int32

Task 28: Extract the day from InvoiceDate and store it in a new column "Day".

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Day'] = df['InvoiceDate'].dt.day


In [ ]:
df['Day']

0         1
1         1
2         1
3         1
4         1
         ..
401599    9
401600    9
401601    9
401602    9
401603    9
Name: Day, Length: 401604, dtype: int32

Task 29: Extract the hour from InvoiceDate and store it in a new column "Hour".

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Hour'] = df['InvoiceDate'].dt.hour


In [ ]:
df['Hour']

0          8
1          8
2          8
3          8
4          8
          ..
401599    12
401600    12
401601    12
401602    12
401603    12
Name: Hour, Length: 401604, dtype: int32

Task 30: Create a column "DayOfWeek" showing which day of the week the transaction occurred.

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['DayOfWeek'] = df['InvoiceDate'].dt.day_name()


In [ ]:
df['DayOfWeek']

0         Wednesday
1         Wednesday
2         Wednesday
3         Wednesday
4         Wednesday
            ...    
401599       Friday
401600       Friday
401601       Friday
401602       Friday
401603       Friday
Name: DayOfWeek, Length: 401604, dtype: object

Task 31: Create a column "Quarter" showing which quarter (Q1, Q2, Q3, Q4) the transaction belongs to.

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Quarter'] = df['InvoiceDate'].dt.to_period('Q').astype(str)


In [ ]:
df['Quarter']

0         2010Q4
1         2010Q4
2         2010Q4
3         2010Q4
4         2010Q4
           ...  
401599    2011Q4
401600    2011Q4
401601    2011Q4
401602    2011Q4
401603    2011Q4
Name: Quarter, Length: 401604, dtype: object

Task 32: Create a column "RevenueCategory" with three levels:

1) "Low" for transactions under £10.

2) "Medium" for transactions between £10 and £100.

3) "High" for transactions above £100

In [ ]:
df['RevenueCategory'] = np.where(df['TotalPrice'] < 10, 'Low',np.where((df['TotalPrice'] >= 10) & (df['TotalPrice'] <= 100),'Medium','High'))


In [ ]:
df[['TotalPrice', 'RevenueCategory']]

TotalPrice RevenueCategory
0            15.30          Medium
1            20.34          Medium
2            22.00          Medium
3            20.34          Medium
4            20.34          Medium
...            ...             ...
401599       10.20          Medium
401600       12.60          Medium
401601       16.60          Medium
401602       16.60          Medium
401603       14.85          Medium

[401604 rows x 2 columns]

Task 33: Create a column "OrderSize" with three levels:

-->"Small" for Quantity less than 5

-->"Medium" for Quantity between 5 and 20

-->"Large" for Quantity greater than 20

In [ ]:
df['OrderSize'] = np.where( df['Quantity'] < 5, 'Small',np.where((df['Quantity'] >= 5) & (df['Quantity'] <= 20),'Medium','Large'))


In [ ]:
df[['OrderSize','Quantity']]

OrderSize  Quantity
0         Medium         6
1         Medium         6
2         Medium         8
3         Medium         6
4         Medium         6
...          ...       ...
401599    Medium        12
401600    Medium         6
401601     Small         4
401602     Small         4
401603     Small         3

[401604 rows x 2 columns]

Task 34: Create a column that shows the length of each product name.

In [ ]:
df['ProductNameLength'] = df['ProductName'].str.len()


In [ ]:
df[['ProductName', 'ProductNameLength']]

ProductName  ProductNameLength
0        WHITE HANGING HEART T-LIGHT HOLDER                 34
1                       WHITE METAL LANTERN                 19
2            CREAM CUPID HEARTS COAT HANGER                 30
3       KNITTED UNION FLAG HOT WATER BOTTLE                 35
4            RED WOOLLY HOTTIE WHITE HEART.                 30
...                                     ...                ...
401599          PACK OF 20 SPACEBOY NAPKINS                 27
401600         CHILDREN'S APRON DOLLY GIRL                  28
401601        CHILDRENS CUTLERY DOLLY GIRL                  29
401602      CHILDRENS CUTLERY CIRCUS PARADE                 31
401603        BAKING SET 9 PIECE RETROSPOT                  29

[401604 rows x 2 columns]

**PART E: Text Data Processing**

Task 35: Convert all product names to uppercase.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   InvoiceNo          401604 non-null  object        
 1   StockCode          401604 non-null  object        
 2   ProductName        401604 non-null  object        
 3   Quantity           401604 non-null  int64         
 4   InvoiceDate        401604 non-null  datetime64[ns]
 5   UnitPrice          401604 non-null  float64       
 6   CustomerID         401604 non-null  int64         
 7   Country            401604 non-null  object        
 8   TotalPrice         401604 non-null  float64       
 9   Year               401604 non-null  int32         
 10  Month              401604 non-null  int32         
 11  Day                401604 non-null  int32         
 12  Hour               401604 non-null  int32         
 13  DayOfWeek          401604 non-null  object  

In [ ]:
df['ProductName'] = df['ProductName'].str.upper()


In [ ]:
df[['ProductName']]

ProductName
0        WHITE HANGING HEART T-LIGHT HOLDER
1                       WHITE METAL LANTERN
2            CREAM CUPID HEARTS COAT HANGER
3       KNITTED UNION FLAG HOT WATER BOTTLE
4            RED WOOLLY HOTTIE WHITE HEART.
...                                     ...
401599          PACK OF 20 SPACEBOY NAPKINS
401600         CHILDREN'S APRON DOLLY GIRL 
401601        CHILDRENS CUTLERY DOLLY GIRL 
401602      CHILDRENS CUTLERY CIRCUS PARADE
401603        BAKING SET 9 PIECE RETROSPOT 

[401604 rows x 1 columns]

Task 36: Remove any extra spaces from the Country column.

In [ ]:
df['Country'] = df['Country'].str.strip()


In [ ]:
df[['Country']]

Country
0       United Kingdom
1       United Kingdom
2       United Kingdom
3       United Kingdom
4       United Kingdom
...                ...
401599          France
401600          France
401601          France
401602          France
401603          France

[401604 rows x 1 columns]

Task 37: Find all products that contain the word "BAG" in their name.

In [ ]:
bag_products = df[df['ProductName'].str.contains('BAG', case=False, na=False)]


In [ ]:
bag_products

InvoiceNo StockCode                      ProductName  Quantity  \
38        536370     22661  CHARLOTTE BAG DOLLY GIRL DESIGN        20   
86        536378     22386          JUMBO BAG PINK POLKADOT        10   
87        536378    85099C   JUMBO  BAG BAROQUE BLACK WHITE        10   
88        536378     21033  JUMBO BAG CHARLIE AND LOLA TOYS        10   
89        536378     20723         STRAWBERRY CHARLOTTE BAG        10   
...          ...       ...                              ...       ...   
401528    581579     23343     JUMBO BAG VINTAGE CHRISTMAS         30   
401529    581579     23344        JUMBO BAG 50'S CHRISTMAS         20   
401530    581579     23581           JUMBO BAG PAISLEY PARK        40   
401557    581581     23681      LUNCH BAG RED VINTAGE DOILY        10   
401560    581583     20725          LUNCH BAG RED RETROSPOT        40   

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
38     2010-12-01 08:45:00       0.85       12583          France        17.0   
86     2010-12-01 09:37:00       1.95       14688  United Kingdom        19.5   
87     2010-12-01 09:37:00       1.95       14688  United Kingdom        19.5   
88     2010-12-01 09:37:00       2.95       14688  United Kingdom        29.5   
89     2010-12-01 09:37:00       0.85       14688  United Kingdom         8.5   
...                    ...        ...         ...             ...         ...   
401528 2011-12-09 12:19:00       1.79       17581  United Kingdom        53.7   
401529 2011-12-09 12:19:00       1.79       17581  United Kingdom        35.8   
401530 2011-12-09 12:19:00       1.79       17581  United Kingdom        71.6   
401557 2011-12-09 12:20:00       1.65       17581  United Kingdom        16.5   
401560 2011-12-09 12:23:00       1.45       13777  United Kingdom        58.0   

        Year  Month  Day  Hour  DayOfWeek Quarter RevenueCategory OrderSize  \
38      2010     12    1     8  Wednesday  2010Q4          Medium    Medium   
86      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
87      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
88      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
89      2010     12    1     9  Wednesday  2010Q4             Low    Medium   
...      ...    ...  ...   ...        ...     ...             ...       ...   
401528  2011     12    9    12     Friday  2011Q4          Medium     Large   
401529  2011     12    9    12     Friday  2011Q4          Medium    Medium   
401530  2011     12    9    12     Friday  2011Q4          Medium     Large   
401557  2011     12    9    12     Friday  2011Q4          Medium    Medium   
401560  2011     12    9    12     Friday  2011Q4          Medium     Large   

        ProductNameLength  
38                     31  
86                     23  
87                     30  
88                     31  
89                     24  
...                   ...  
401528                 28  
401529                 25  
401530                 22  
401557                 27  
401560                 23  

[38727 rows x 18 columns]

Task 38: Find all products whose names start with "WHITE".

In [ ]:
white_products = df[df['ProductName'].str.startswith('WHITE', na=False)]


In [ ]:
white_products

InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
49        536373    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
50        536373     71053                  WHITE METAL LANTERN         6   
66        536375    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
...          ...       ...                                  ...       ...   
400927    581472    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
401040    581476     21479        WHITE SKULL HOT WATER BOTTLE          4   
401281    581502     23210     WHITE ROCKING HORSE HAND PAINTED        12   
401348    581538     21673  WHITE SPOT BLUE CERAMIC DRAWER KNOB         1   
401407    581567     21479        WHITE SKULL HOT WATER BOTTLE          4   

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom       15.30   
1      2010-12-01 08:26:00       3.39       17850  United Kingdom       20.34   
49     2010-12-01 09:02:00       2.55       17850  United Kingdom       15.30   
50     2010-12-01 09:02:00       3.39       17850  United Kingdom       20.34   
66     2010-12-01 09:32:00       2.55       17850  United Kingdom       15.30   
...                    ...        ...         ...             ...         ...   
400927 2011-12-08 19:55:00       2.95       15796  United Kingdom       17.70   
401040 2011-12-09 08:48:00       4.25       12433          Norway       17.00   
401281 2011-12-09 10:51:00       1.25       15910  United Kingdom       15.00   
401348 2011-12-09 11:34:00       1.45       14446  United Kingdom        1.45   
401407 2011-12-09 11:56:00       4.25       16626  United Kingdom       17.00   

        Year  Month  Day  Hour  DayOfWeek Quarter RevenueCategory OrderSize  \
0       2010     12    1     8  Wednesday  2010Q4          Medium    Medium   
1       2010     12    1     8  Wednesday  2010Q4          Medium    Medium   
49      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
50      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
66      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
...      ...    ...  ...   ...        ...     ...             ...       ...   
400927  2011     12    8    19   Thursday  2011Q4          Medium    Medium   
401040  2011     12    9     8     Friday  2011Q4          Medium     Small   
401281  2011     12    9    10     Friday  2011Q4          Medium    Medium   
401348  2011     12    9    11     Friday  2011Q4             Low     Small   
401407  2011     12    9    11     Friday  2011Q4          Medium     Small   

        ProductNameLength  
0                      34  
1                      19  
49                     34  
50                     19  
66                     34  
...                   ...  
400927                 34  
401040                 29  
401281                 32  
401348                 35  
401407                 29  

[5532 rows x 18 columns]

Task 39: Find all products whose names end with "HOLDER".

In [ ]:
holder_products = df[df['ProductName'].str.endswith('HOLDER', na=False)]


In [ ]:
holder_products

InvoiceNo StockCode                         ProductName  Quantity  \
0         536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
6         536365     21730   GLASS STAR FROSTED T-LIGHT HOLDER         6   
49        536373    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
64        536373     21730   GLASS STAR FROSTED T-LIGHT HOLDER         6   
66        536375    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
...          ...       ...                                 ...       ...   
401411   C581569     84978    HANGING HEART JAR T-LIGHT HOLDER        -1   
401436    581571     85053          FRENCH ENAMEL CANDLEHOLDER         2   
401520    581579     22197                      POPCORN HOLDER        24   
401567    581585     22460      EMBOSSED GLASS TEALIGHT HOLDER        12   
401571    581585     84945  MULTI COLOUR SILVER T-LIGHT HOLDER        24   

               InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0      2010-12-01 08:26:00       2.55       17850  United Kingdom       15.30   
6      2010-12-01 08:26:00       4.25       17850  United Kingdom       25.50   
49     2010-12-01 09:02:00       2.55       17850  United Kingdom       15.30   
64     2010-12-01 09:02:00       4.25       17850  United Kingdom       25.50   
66     2010-12-01 09:32:00       2.55       17850  United Kingdom       15.30   
...                    ...        ...         ...             ...         ...   
401411 2011-12-09 11:58:00       1.25       17315  United Kingdom       -1.25   
401436 2011-12-09 12:00:00       2.10       15311  United Kingdom        4.20   
401520 2011-12-09 12:19:00       0.85       17581  United Kingdom       20.40   
401567 2011-12-09 12:31:00       1.25       15804  United Kingdom       15.00   
401571 2011-12-09 12:31:00       0.85       15804  United Kingdom       20.40   

        Year  Month  Day  Hour  DayOfWeek Quarter RevenueCategory OrderSize  \
0       2010     12    1     8  Wednesday  2010Q4          Medium    Medium   
6       2010     12    1     8  Wednesday  2010Q4          Medium    Medium   
49      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
64      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
66      2010     12    1     9  Wednesday  2010Q4          Medium    Medium   
...      ...    ...  ...   ...        ...     ...             ...       ...   
401411  2011     12    9    11     Friday  2011Q4             Low     Small   
401436  2011     12    9    12     Friday  2011Q4             Low     Small   
401520  2011     12    9    12     Friday  2011Q4          Medium     Large   
401567  2011     12    9    12     Friday  2011Q4          Medium    Medium   
401571  2011     12    9    12     Friday  2011Q4          Medium     Large   

        ProductNameLength  
0                      34  
6                      33  
49                     34  
64                     33  
66                     34  
...                   ...  
401411                 32  
401436                 26  
401520                 14  
401567                 30  
401571                 34  

[10794 rows x 18 columns]

Task 40: Replace "United Kingdom" with "UK" in the Country column

In [ ]:
df['Country'] = df['Country'].str.replace('United Kingdom', 'UK', regex=False)

In [ ]:
df['Country']

0             UK
1             UK
2             UK
3             UK
4             UK
           ...  
401599    France
401600    France
401601    France
401602    France
401603    France
Name: Country, Length: 401604, dtype: object

**PART F: Data Selection and Filtering**

Task 42: Select only the columns: InvoiceNo, ProductName, Quantity, UnitPrice, Country.

In [ ]:
selected_df = df[['InvoiceNo', 'ProductName', 'Quantity', 'UnitPrice', 'Country']]


In [ ]:
selected_df

InvoiceNo                          ProductName  Quantity  UnitPrice  \
0         536365   WHITE HANGING HEART T-LIGHT HOLDER         6       2.55   
1         536365                  WHITE METAL LANTERN         6       3.39   
2         536365       CREAM CUPID HEARTS COAT HANGER         8       2.75   
3         536365  KNITTED UNION FLAG HOT WATER BOTTLE         6       3.39   
4         536365       RED WOOLLY HOTTIE WHITE HEART.         6       3.39   
...          ...                                  ...       ...        ...   
401599    581587          PACK OF 20 SPACEBOY NAPKINS        12       0.85   
401600    581587         CHILDREN'S APRON DOLLY GIRL          6       2.10   
401601    581587        CHILDRENS CUTLERY DOLLY GIRL          4       4.15   
401602    581587      CHILDRENS CUTLERY CIRCUS PARADE         4       4.15   
401603    581587        BAKING SET 9 PIECE RETROSPOT          3       4.95   

       Country  
0           UK  
1           UK  
2           UK  
3           UK  
4           UK  
...        ...  
401599  France  
401600  France  
401601  France  
401602  France  
401603  France  

[401604 rows x 5 columns]

Task 43: Display transactions from Germany only.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   InvoiceNo          401604 non-null  object        
 1   StockCode          401604 non-null  object        
 2   ProductName        401604 non-null  object        
 3   Quantity           401604 non-null  int64         
 4   InvoiceDate        401604 non-null  datetime64[ns]
 5   UnitPrice          401604 non-null  float64       
 6   CustomerID         401604 non-null  int64         
 7   Country            401604 non-null  object        
 8   TotalPrice         401604 non-null  float64       
 9   Year               401604 non-null  int32         
 10  Month              401604 non-null  int32         
 11  Day                401604 non-null  int32         
 12  Hour               401604 non-null  int32         
 13  DayOfWeek          401604 non-null  object  

In [ ]:
germany_transactions = df[df['Country'] == 'Germany'][['Country','InvoiceNo', 'StockCode', 'ProductName', 'Quantity']]
germany_transactions


Country InvoiceNo StockCode                          ProductName  \
1083    Germany    536527     22809              SET OF 6 T-LIGHTS SANTA   
1084    Germany    536527     84347  ROTATING SILVER ANGELS T-LIGHT HLDR   
1085    Germany    536527     84945   MULTI COLOUR SILVER T-LIGHT HOLDER   
1086    Germany    536527     22242        5 HOOK HANGER MAGIC TOADSTOOL   
1087    Germany    536527     22244           3 HOOK HANGER MAGIC GARDEN   
...         ...       ...       ...                                  ...   
401496  Germany    581578     22993         SET OF 4 PANTRY JELLY MOULDS   
401497  Germany    581578     22907     PACK OF 20 NAPKINS PANTRY DESIGN   
401498  Germany    581578     22908        PACK OF 20 NAPKINS RED APPLES   
401499  Germany    581578     23215     JINGLE BELL HEART ANTIQUE SILVER   
401500  Germany    581578     22736          RIBBON REEL MAKING SNOWMEN    

        Quantity  
1083           6  
1084           6  
1085          12  
1086          12  
1087          12  
...          ...  
401496        12  
401497        12  
401498        12  
401499        12  
401500        10  

[9480 rows x 5 columns]

Task 44: Display transactions where Quantity is greater than 50.

In [ ]:
high_quantity_transactions = df[df['Quantity'] > 50][['InvoiceNo', 'StockCode', 'ProductName', 'Quantity']]
high_quantity_transactions


InvoiceNo StockCode                         ProductName  Quantity
46        536371     22086     PAPER CHAIN KIT 50'S CHRISTMAS         80
83        536376     21733    RED HANGING HEART T-LIGHT HOLDER        64
96        536378     21212     PACK OF 72 RETROSPOT CAKE CASES       120
102       536378    85071B  RED CHARLIE+LOLA PERSONAL DOORSIGN        96
176       536386    85099C      JUMBO  BAG BAROQUE BLACK WHITE       100
...          ...       ...                                 ...       ...
401397    581566     23404          HOME SWEET HOME BLACKBOARD       144
401398    581567     21417                   COCKLE SHELL DISH        84
401406    581567     21326    AGED GLASS SILVER T-LIGHT HOLDER       144
401441    581571     23167      SMALL CERAMIC TOP STORAGE JAR         96
401562    581584     20832    RED FLOCK LOVE HEART PHOTO FRAME        72

[11603 rows x 4 columns]

Task 45: Display transactions where UnitPrice is between £5 and £10.

In [ ]:
unitprice_5_10_transactions = df[(df['UnitPrice'] >= 5) & (df['UnitPrice'] <= 10)][['InvoiceNo', 'StockCode', 'ProductName', 'UnitPrice']]
unitprice_5_10_transactions


InvoiceNo StockCode                     ProductName  UnitPrice
5         536365     22752    SET 7 BABUSHKA NESTING BOXES       7.65
16        536367     22622  BOX OF VINTAGE ALPHABET BLOCKS       9.95
17        536367     21754        HOME BUILDING BLOCK WORD       5.95
18        536367     21755        LOVE BUILDING BLOCK WORD       5.95
19        536367     21777     RECIPE BOX WITH METAL HEART       7.95
...          ...       ...                             ...        ...
401550    581580     21351        CINAMMON & ORANGE WREATH       6.75
401553    581580     79321                   CHILLI LIGHTS       5.75
401573    581585     23356           LOVE HOT WATER BOTTLE       5.95
401587    581586     21217   RED RETROSPOT ROUND CAKE TINS       8.95
401588    581586     20685           DOORMAT RED RETROSPOT       7.08

[41239 rows x 4 columns]

Task 46: Display transactions from France with Quantity greater than 20.

In [ ]:
france_high_quantity = df[(df['Country'] == 'France') & (df['Quantity'] > 20)][['InvoiceNo', 'StockCode', 'ProductName', 'Quantity', 'Country']]
france_high_quantity


InvoiceNo StockCode                         ProductName  Quantity  \
26        536370     22728           ALARM CLOCK BAKELIKE PINK        24   
27        536370     22727           ALARM CLOCK BAKELIKE RED         24   
30        536370     21883                    STARS GIFT TAPE         24   
31        536370     10002         INFLATABLE POLITICAL GLOBE         48   
32        536370     21791  VINTAGE HEADS AND TAILS CARD GAME         24   
...          ...       ...                                 ...       ...   
396280    581001     23084                  RABBIT NIGHT LIGHT        24   
396294    581001     22726          ALARM CLOCK BAKELIKE GREEN        24   
397899    581171     22966       GINGERBREAD MAN COOKIE CUTTER        24   
397910    581171     84077   WORLD WAR 2 GLIDERS ASSTD DESIGNS        48   
397917    581171     23084                  RABBIT NIGHT LIGHT        24   

       Country  
26      France  
27      France  
30      France  
31      France  
32      France  
...        ...  
396280  France  
396294  France  
397899  France  
397910  France  
397917  France  

[1411 rows x 5 columns]

Task 47: Display transactions from December 2010.

In [ ]:
dec_2010_df = df[(df['Year'] == 2010) & (df['Month'] == 12)][['InvoiceNo', 'StockCode', 'ProductName', 'InvoiceDate']]
dec_2010_df


InvoiceNo StockCode                          ProductName  \
0        536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1        536365     71053                  WHITE METAL LANTERN   
2        536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3        536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4        536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   
...         ...       ...                                  ...   
26349    539988     84380    SET OF 3 BUTTERFLY COOKIE CUTTERS   
26350    539988    84849D                HOT BATHS SOAP HOLDER   
26351    539988    84849B               FAIRY SOAP SOAP HOLDER   
26352    539988     22854          CREAM SWEETHEART EGG HOLDER   
26353    539988    47559B                  TEA TIME OVEN GLOVE   

              InvoiceDate  
0     2010-12-01 08:26:00  
1     2010-12-01 08:26:00  
2     2010-12-01 08:26:00  
3     2010-12-01 08:26:00  
4     2010-12-01 08:26:00  
...                   ...  
26349 2010-12-23 16:06:00  
26350 2010-12-23 16:06:00  
26351 2010-12-23 16:06:00  
26352 2010-12-23 16:06:00  
26353 2010-12-23 16:06:00  

[26354 rows x 4 columns]

Task 48: Display transactions that occurred on weekends

In [ ]:
weekend_transactions = df[df['DayOfWeek'].isin(['Saturday', 'Sunday'])][['InvoiceNo', 'StockCode', 'ProductName', 'DayOfWeek']]
weekend_transactions


InvoiceNo StockCode                          ProductName DayOfWeek
5027      537037     22114    HOT WATER BOTTLE TEA AND SYMPATHY    Sunday
5028      537037     21485     RETROSPOT HEART HOT WATER BOTTLE    Sunday
5029      537037     22835      HOT WATER BOTTLE I AM SO POORLY    Sunday
5030      537037    84029E       RED WOOLLY HOTTIE WHITE HEART.    Sunday
5031      537037    84029G  KNITTED UNION FLAG HOT WATER BOTTLE    Sunday
...          ...       ...                                  ...       ...
390291    580536     21156            RETROSPOT CHILDRENS APRON    Sunday
390292    580536     21880                   RED RETROSPOT TAPE    Sunday
390293    580536     22090              PAPER BUNTING RETROSPOT    Sunday
390294    580536     22628     PICNIC BOXES SET OF 3 RETROSPOT     Sunday
390295    580536      POST                              POSTAGE    Sunday

[61673 rows x 4 columns]

Task 49: Display the top 10 transactions by TotalPrice.

In [ ]:
top_10_transactions = df.sort_values(by='TotalPrice', ascending=False)[['InvoiceNo', 'StockCode', 'ProductName', 'TotalPrice']].head(10)
top_10_transactions


InvoiceNo StockCode                          ProductName  TotalPrice
401131    581483     23843          PAPER CRAFT , LITTLE BIRDIE   168469.60
37511     541431     23166       MEDIUM CERAMIC TOP STORAGE JAR    77183.60
157405    556444     22502       PICNIC BASKET WICKER 60 PIECES    38970.00
119907    551697      POST                              POSTAGE     8142.75
252000    567423     23243  SET OF TEA COFFEE SUGAR TINS PANTRY     7144.72
111014    550461     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR     6539.40
33109     540815     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR     6539.40
312033    573003     23084                   RABBIT NIGHT LIGHT     4992.00
33107     540815    85123A   WHITE HANGING HEART T-LIGHT HOLDER     4921.50
111010    550461    85123A   WHITE HANGING HEART T-LIGHT HOLDER     4632.00

Task 50: Display the bottom 15 transactions by TotalPrice.

In [ ]:
bottom_15_transactions = df.sort_values(by='TotalPrice', ascending=True)[['InvoiceNo', 'StockCode', 'ProductName', 'TotalPrice']].head(15)
bottom_15_transactions


InvoiceNo StockCode                         ProductName  TotalPrice
401132   C581484     23843         PAPER CRAFT , LITTLE BIRDIE  -168469.60
37516    C541433     23166      MEDIUM CERAMIC TOP STORAGE JAR   -77183.60
157406   C556445         M                              MANUAL   -38970.00
312797   C573079         M                              MANUAL    -8322.12
119809   C551685      POST                             POSTAGE    -8142.75
119916   C551699         M                              MANUAL    -6930.00
110949   C550456     21108  FAIRY CAKE FLANNEL ASSORTED COLOUR    -6539.40
110947   C550456    85123A  WHITE HANGING HEART T-LIGHT HOLDER    -4921.50
110945   C550456     48185                  DOORMAT FAIRY CAKE    -4522.50
189323   C560372         M                              MANUAL    -4287.63
299195   C571750         M                              MANUAL    -3949.32
253138   C567527     23113               PANTRY CHOPPING BOARD    -3825.36
110948   C550456     21175         GIN + TONIC DIET METAL SIGN    -3700.00
110946   C550456    47566B              TEA TIME PARTY BUNTING    -3315.00
209184   C562647         M                              MANUAL    -3155.95

Task 51: Find all transactions from either UK, Germany, or France

In [ ]:
uk_germany_france_transactions = df[df['Country'].isin(['United Kingdom', 'Germany', 'France'])][['InvoiceNo', 'StockCode', 'ProductName', 'Country']]
uk_germany_france_transactions


InvoiceNo StockCode                      ProductName Country
26        536370     22728        ALARM CLOCK BAKELIKE PINK  France
27        536370     22727        ALARM CLOCK BAKELIKE RED   France
28        536370     22726       ALARM CLOCK BAKELIKE GREEN  France
29        536370     21724  PANDA AND BUNNIES STICKER SHEET  France
30        536370     21883                 STARS GIFT TAPE   France
...          ...       ...                              ...     ...
401599    581587     22613      PACK OF 20 SPACEBOY NAPKINS  France
401600    581587     22899     CHILDREN'S APRON DOLLY GIRL   France
401601    581587     23254    CHILDRENS CUTLERY DOLLY GIRL   France
401602    581587     23255  CHILDRENS CUTLERY CIRCUS PARADE  France
401603    581587     22138    BAKING SET 9 PIECE RETROSPOT   France

[17955 rows x 4 columns]

Task 52: Find transactions where TotalPrice is above the 95th percentile.

In [ ]:
totalprice_95th = df['TotalPrice'].quantile(0.95)
high_value_transactions = df[df['TotalPrice'] > totalprice_95th][['InvoiceNo', 'StockCode', 'ProductName', 'TotalPrice']]
high_value_transactions


InvoiceNo StockCode                          ProductName  TotalPrice
26        536370     22728            ALARM CLOCK BAKELIKE PINK       90.00
27        536370     22727            ALARM CLOCK BAKELIKE RED        90.00
34        536370     22326  ROUND SNACK BOXES SET OF4 WOODLAND        70.80
40        536370     22900      SET 2 TEA TOWELS I LOVE LONDON        70.80
46        536371     22086      PAPER CHAIN KIT 50'S CHRISTMAS       204.00
...          ...       ...                                  ...         ...
401522    581579     23313            VINTAGE CHRISTMAS BUNTING       74.25
401530    581579     23581               JUMBO BAG PAISLEY PARK       71.60
401563    581584     85038      6 CHOCOLATE LOVE HEART T-LIGHTS       88.80
401587    581586     21217        RED RETROSPOT ROUND CAKE TINS      214.80
401588    581586     20685                DOORMAT RED RETROSPOT       70.80

[19599 rows x 4 columns]

**PART G: Sorting Operations**

**Task 53:** Sort the entire dataset by InvoiceDate in ascending order.

In [ ]:
sorted_by_date = df.sort_values(by='InvoiceDate', ascending=True)
sorted_by_date


InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
401591    581587     22555            PLASTERS IN TIN STRONGMAN        12   
401590    581587     22556       PLASTERS IN TIN CIRCUS PARADE         12   
401602    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
401595    581587     22730           ALARM CLOCK BAKELIKE IVORY         4   
401603    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID Country  TotalPrice  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK       15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK       22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
...                    ...        ...         ...     ...         ...   ...   
401591 2011-12-09 12:50:00       1.65       12680  France       19.80  2011   
401590 2011-12-09 12:50:00       1.65       12680  France       19.80  2011   
401602 2011-12-09 12:50:00       4.15       12680  France       16.60  2011   
401595 2011-12-09 12:50:00       3.75       12680  France       15.00  2011   
401603 2011-12-09 12:50:00       4.95       12680  France       14.85  2011   

        Month  Day  Hour  DayOfWeek Quarter RevenueCategory OrderSize  \
0          12    1     8  Wednesday  2010Q4          Medium    Medium   
1          12    1     8  Wednesday  2010Q4          Medium    Medium   
2          12    1     8  Wednesday  2010Q4          Medium    Medium   
3          12    1     8  Wednesday  2010Q4          Medium    Medium   
4          12    1     8  Wednesday  2010Q4          Medium    Medium   
...       ...  ...   ...        ...     ...             ...       ...   
401591     12    9    12     Friday  2011Q4          Medium    Medium   
401590     12    9    12     Friday  2011Q4          Medium    Medium   
401602     12    9    12     Friday  2011Q4          Medium     Small   
401595     12    9    12     Friday  2011Q4          Medium     Small   
401603     12    9    12     Friday  2011Q4          Medium     Small   

        ProductNameLength  
0                      34  
1                      19  
2                      30  
3                      35  
4                      30  
...                   ...  
401591                 25  
401590                 30  
401602                 31  
401595                 26  
401603                 29  

[401604 rows x 18 columns]

Task 54: Sort the dataset by TotalPrice in descending order

In [ ]:

sorted_by_totalprice = df.sort_values(by='TotalPrice', ascending=False)
sorted_by_totalprice

InvoiceNo StockCode                          ProductName  Quantity  \
401131    581483     23843          PAPER CRAFT , LITTLE BIRDIE     80995   
37511     541431     23166       MEDIUM CERAMIC TOP STORAGE JAR     74215   
157405    556444     22502       PICNIC BASKET WICKER 60 PIECES        60   
119907    551697      POST                              POSTAGE         1   
252000    567423     23243  SET OF TEA COFFEE SUGAR TINS PANTRY      1412   
...          ...       ...                                  ...       ...   
119809   C551685      POST                              POSTAGE        -1   
312797   C573079         M                               MANUAL        -2   
157406   C556445         M                               MANUAL        -1   
37516    C541433     23166       MEDIUM CERAMIC TOP STORAGE JAR    -74215   
401132   C581484     23843          PAPER CRAFT , LITTLE BIRDIE    -80995   

               InvoiceDate  UnitPrice  CustomerID Country  TotalPrice  Year  \
401131 2011-12-09 09:15:00       2.08       16446      UK   168469.60  2011   
37511  2011-01-18 10:01:00       1.04       12346      UK    77183.60  2011   
157405 2011-06-10 15:28:00     649.50       15098      UK    38970.00  2011   
119907 2011-05-03 13:46:00    8142.75       16029      UK     8142.75  2011   
252000 2011-09-20 11:05:00       5.06       17450      UK     7144.72  2011   
...                    ...        ...         ...     ...         ...   ...   
119809 2011-05-03 12:51:00    8142.75       16029      UK    -8142.75  2011   
312797 2011-10-27 14:15:00    4161.06       12536  France    -8322.12  2011   
157406 2011-06-10 15:31:00   38970.00       15098      UK   -38970.00  2011   
37516  2011-01-18 10:17:00       1.04       12346      UK   -77183.60  2011   
401132 2011-12-09 09:27:00       2.08       16446      UK  -168469.60  2011   

        Month  Day  Hour DayOfWeek Quarter RevenueCategory OrderSize  \
401131     12    9     9    Friday  2011Q4            High     Large   
37511       1   18    10   Tuesday  2011Q1            High     Large   
157405      6   10    15    Friday  2011Q2            High     Large   
119907      5    3    13   Tuesday  2011Q2            High     Small   
252000      9   20    11   Tuesday  2011Q3            High     Large   
...       ...  ...   ...       ...     ...             ...       ...   
119809      5    3    12   Tuesday  2011Q2             Low     Small   
312797     10   27    14  Thursday  2011Q4             Low     Small   
157406      6   10    15    Friday  2011Q2             Low     Small   
37516       1   18    10   Tuesday  2011Q1             Low     Small   
401132     12    9     9    Friday  2011Q4             Low     Small   

        ProductNameLength  
401131                 27  
37511                  30  
157405                 30  
119907                  7  
252000                 35  
...                   ...  
119809                  7  
312797                  6  
157406                  6  
37516                  30  
401132                 27  

[401604 rows x 18 columns]

Task 55: Sort by Country (ascending) and then by TotalPrice (descending).

In [ ]:
sorted_country_totalprice = df.sort_values(by=['Country', 'TotalPrice'], ascending=[True, False])[['InvoiceNo', 'StockCode', 'ProductName', 'Country', 'TotalPrice']]
sorted_country_totalprice


InvoiceNo StockCode                          ProductName      Country  \
348972    576394     23084                   RABBIT NIGHT LIGHT    Australia   
217754    563614     22940            FELTCRAFT CHRISTMAS FAIRY    Australia   
70370     545475     21217        RED RETROSPOT ROUND CAKE TINS    Australia   
217824    563614     23314         VINTAGE CHRISTMAS TABLECLOTH    Australia   
28351     540267     22720    SET OF 3 CAKE TINS PANTRY DESIGN     Australia   
...          ...       ...                                  ...          ...   
199826    561661    47343A      FUSCHIA FLOWER PURSE WITH BEADS  Unspecified   
199707    561658    47574A  ENGLISH ROSE SCENTED HANGING FLOWER  Unspecified   
199771    561658    47348A        FUSCHIA VOILE POINTY SHOE DEC  Unspecified   
199821    561661     22396        MAGNETS PACK OF 4 RETRO PHOTO  Unspecified   
199796    561661    79063C    RETRO PILL BOX KEY CHAIN,THE KING  Unspecified   

        TotalPrice  
348972     1718.40  
217754     1260.00  
70370      1074.00  
217824     1039.00  
28351      1020.00  
...            ...  
199826        0.83  
199707        0.75  
199771        0.39  
199821        0.39  
199796        0.19  

[401604 rows x 5 columns]

Task 56: Find the 20 highest-value transactions.

In [ ]:
highest_20_transactions = df.sort_values(by='TotalPrice', ascending=False)[['InvoiceNo', 'StockCode', 'ProductName', 'TotalPrice']].head(20)
highest_20_transactions


InvoiceNo StockCode                          ProductName  TotalPrice
401131    581483     23843          PAPER CRAFT , LITTLE BIRDIE   168469.60
37511     541431     23166       MEDIUM CERAMIC TOP STORAGE JAR    77183.60
157405    556444     22502       PICNIC BASKET WICKER 60 PIECES    38970.00
119907    551697      POST                              POSTAGE     8142.75
252000    567423     23243  SET OF TEA COFFEE SUGAR TINS PANTRY     7144.72
111014    550461     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR     6539.40
33109     540815     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR     6539.40
312033    573003     23084                   RABBIT NIGHT LIGHT     4992.00
33107     540815    85123A   WHITE HANGING HEART T-LIGHT HOLDER     4921.50
111010    550461    85123A   WHITE HANGING HEART T-LIGHT HOLDER     4632.00
33169     540818     48185                   DOORMAT FAIRY CAKE     4522.50
173829    558526     23173                REGENCY TEAPOT ROSES      4401.00
111012    550461     48185                   DOORMAT FAIRY CAKE     4254.50
206823    562439     84879        ASSORTED COLOUR BIRD ORNAMENT     4176.00
312773    573077         M                               MANUAL     4161.06
312798    573080         M                               MANUAL     4161.06
32539     540689     22470                HEART OF WICKER LARGE     4121.64
299197    571751         M                               MANUAL     3949.32
396953    581115     22413      METAL SIGN TAKE IT OR LEAVE IT      3861.00
10678     537659     21623         VINTAGE UNION JACK MEMOBOARD     3828.00

Task 57: Find the 20 lowest-value transactions (excluding returns).

In [ ]:
lowest_20_transactions = df[(df['Quantity'] > 0) & (df['TotalPrice'] > 0)] \
    .sort_values(by='TotalPrice', ascending=True)[['InvoiceNo', 'StockCode', 'ProductName', 'TotalPrice']] \
    .head(20)

lowest_20_transactions


InvoiceNo     StockCode                          ProductName  \
260900    568200          PADS           PADS TO MATCH ALL CUSHIONS   
108733    550193          PADS           PADS TO MATCH ALL CUSHIONS   
197044    561226          PADS           PADS TO MATCH ALL CUSHIONS   
262732    568375  BANK CHARGES                         BANK CHARGES   
373219    578757         16216        LETTER SHAPE PENCIL SHARPENER   
201821    561894             M                               MANUAL   
181325    559509         17038       PORCELAIN BUDAH INCENSE HOLDER   
171948    558198         17038       PORCELAIN BUDAH INCENSE HOLDER   
370903    578479         17038       PORCELAIN BUDAH INCENSE HOLDER   
302763    572103         16048      TEATIME ROUND PENCIL SHARPENER    
97197     548711        47013A         WINE BOTTLE DRESSING LT.BLUE   
195127    561036         85204         HANGING WOOD AND FELT FLOWER   
300287    571909         16048      TEATIME ROUND PENCIL SHARPENER    
112961    550651         21401                   BLUE PUDDING SPOON   
109354    550298         20668      DISCO BALL CHRISTMAS DECORATION   
232592    565426         85204         HANGING WOOD AND FELT FLOWER   
283213    570238         16048      TEATIME ROUND PENCIL SHARPENER    
341995    575856         16219         HOUSE SHAPE PENCIL SHARPENER   
188931    560359         16008  SMALL FOLDING SCISSOR(POINTED EDGE)   
181472    559525         21402                      RED  EGG  SPOON   

        TotalPrice  
260900       0.001  
108733       0.001  
197044       0.001  
262732       0.001  
373219       0.060  
201821       0.080  
181325       0.100  
171948       0.100  
370903       0.100  
302763       0.120  
97197        0.120  
195127       0.120  
300287       0.120  
112961       0.120  
109354       0.120  
232592       0.120  
283213       0.120  
341995       0.120  
188931       0.120  
181472       0.120


**PART H: Aggregation and Summary Statistics**

Task 58: Calculate the total revenue generated across all transactions.

In [ ]:
total_revenue = df['TotalPrice'].sum()
total_revenue


np.float64(8278519.4240000015)

Task 59: Calculate the average transaction value.

In [ ]:
average_transaction = df['TotalPrice'].mean()
average_transaction


np.float64(20.613637872132752)

Task 60: Find the maximum and minimum transaction values.

In [ ]:
max_transaction = df['TotalPrice'].max()
min_transaction = df['TotalPrice'].min()
max_transaction, min_transaction


(168469.6, -168469.6)

Task 61: Calculate the total number of unique customers.

In [ ]:
unique_customers = df['CustomerID'].nunique()
unique_customers


4372

Task 62: Calculate the total number of unique products sold.

In [ ]:
unique_products = df['ProductName'].nunique()
unique_products


3896

Task 63: Find out how many unique countries are represented in the data.

In [ ]:
unique_countries = df['Country'].nunique()
unique_countries


37

Task 64: Calculate the average number of items per transaction.

In [ ]:
average_items = df['Quantity'].mean()
average_items


np.float64(12.183272576966365)

Task 65: Find which product appears most frequently in transactions.

In [ ]:
most_frequent_product = df['ProductName'].value_counts().idxmax()
most_frequent_count = df['ProductName'].value_counts().max()
most_frequent_product, most_frequent_count


('WHITE HANGING HEART T-LIGHT HOLDER', 2058)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   InvoiceNo          401604 non-null  object        
 1   StockCode          401604 non-null  object        
 2   ProductName        401604 non-null  object        
 3   Quantity           401604 non-null  int64         
 4   InvoiceDate        401604 non-null  datetime64[ns]
 5   UnitPrice          401604 non-null  float64       
 6   CustomerID         401604 non-null  int64         
 7   Country            401604 non-null  object        
 8   TotalPrice         401604 non-null  float64       
 9   Year               401604 non-null  int32         
 10  Month              401604 non-null  int32         
 11  Day                401604 non-null  int32         
 12  Hour               401604 non-null  int32         
 13  DayOfWeek          401604 non-null  object  

# PART I: Country-wise Analysis

Task 66: Calculate total revenue for each country.

In [ ]:
country_revenue = df.groupby('Country')['TotalPrice'].sum()
country_revenue


Country
Australia                137009.770
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20076.390
Cyprus                    12858.760
Czech Republic              707.720
Denmark                   18768.140
EIRE                     250001.780
European Community         1291.750
Finland                   22326.740
France                   196626.050
Germany                  221509.470
Greece                     4710.520
Iceland                    4310.000
Israel                     6988.400
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal                  28995.760
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54756.030
Sweden                    36585.410
Switzerland               55739.400
UK                      6747156.154
USA                        1730.920
United Arab Emirates       1902.280
Unspecified                2660.770
Name: TotalPrice, dtype: float64

Task 67: Find the top 10 countries by total revenue.

In [ ]:
country_revenue = df.groupby('Country')['TotalPrice'].sum()
top_10_countries = country_revenue.sort_values(ascending=False).head(10)
top_10_countries


Country
UK             6747156.154
Netherlands     284661.540
EIRE            250001.780
Germany         221509.470
France          196626.050
Australia       137009.770
Switzerland      55739.400
Spain            54756.030
Belgium          40910.960
Sweden           36585.410
Name: TotalPrice, dtype: float64

Task 68: Calculate the number of transactions per country.

In [ ]:
transactions_per_country = df.groupby('Country')['InvoiceNo'].count()
transactions_per_country


Task 69: Calculate the average transaction value for each country.

In [ ]:
avg_transaction_value = df.groupby('Country')['TotalPrice'].mean()
avg_transaction_value


Country
Australia               108.910787
Austria                  25.322494
Bahrain                  32.258824
Belgium                  19.773301
Brazil                   35.737500
Canada                   24.280662
Channel Islands          26.520991
Cyprus                   21.045434
Czech Republic           23.590667
Denmark                  48.247147
EIRE                     33.445054
European Community       21.176230
Finland                  32.124806
France                   23.200714
Germany                  23.365978
Greece                   32.263836
Iceland                  23.681319
Israel                   28.293117
Italy                    21.034259
Japan                    98.716816
Lebanon                  37.641778
Lithuania                47.458857
Malta                    19.728110
Netherlands             120.059696
Norway                   32.378877
Poland                   21.152903
Portugal                 19.711598
RSA                      17.281207
Saudi Arabia             13.117000
Singapore                39.827031
Spain                    21.659822
Sweden                   79.360976
Switzerland              29.696004
UK                       18.914008
USA                       5.948179
United Arab Emirates     27.974706
Unspecified              11.040539
Name: TotalPrice, dtype: float64

Task 70: Find which country has the highest average order value.

In [ ]:
highest_avg_order_country = df.groupby('Country')['TotalPrice'].mean().sort_values(ascending=False).head(1)
highest_avg_order_country


Country
Netherlands    120.059696
Name: TotalPrice, dtype: float64

In [ ]:
highest_avg_order = avg_transaction_value.sort_values(ascending=False).head(1)
highest_avg_order

Country
Netherlands    120.059696
Name: TotalPrice, dtype: float64

Task 71: Calculate the total quantity of products sold to each country.

In [ ]:
total_quantity = df.groupby('Country')['Quantity'].sum()
total_quantity

Country
Australia                 83643
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9473
Cyprus                     6296
Czech Republic              592
Denmark                    8188
EIRE                     136187
European Community          497
Finland                   10666
France                   109806
Germany                  117341
Greece                     1556
Iceland                    2458
Israel                     3987
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16017
RSA                         352
Saudi Arabia                 75
Singapore                  5234
Spain                     26817
Sweden                    35632
Switzerland               29778
UK                      3994870
USA                        1034
United Arab Emirates        982
Unspecified                1785
Name: Quantity, dtype: int64

Task 72: Find the country with the most unique customers.

In [ ]:
most_unique_customers_country = df.groupby('Country')['CustomerID'].nunique().sort_values(ascending=False).head(1)
most_unique_customers_country


# PART J: Time-based Analysis

Task 73: Calculate total revenue for each month.

In [ ]:
monthly_revenue = df.groupby('Month')['TotalPrice'].sum()
monthly_revenue


Month
1      473731.900
2      435534.070
3      578576.210
4      425222.671
5      647011.670
6      606862.520
7      573112.321
8      615078.090
9      929356.232
10     973306.380
11    1126815.070
12     893912.290
Name: TotalPrice, dtype: float64

Task 74: Find which month had the highest sales.

In [ ]:
monthly_revenue = df.groupby('Month')['TotalPrice'].sum()
monthly_revenue
highest_sales_month = monthly_revenue.sort_values(ascending=False).head(1)
highest_sales_month



Month
11    1126815.07
Name: TotalPrice, dtype: float64

In [ ]:
highest_sale = df.groupby('Month')['TotalPrice'].sum().sort_values(ascending=False).head(1)
highest_sale

Month
11    1126815.07
Name: TotalPrice, dtype: float64

Task 75: Calculate revenue for each quarter.

In [ ]:
revenue_per_quarter = df.groupby('Quarter')['TotalPrice'].sum()
revenue_per_quarter

Quarter
2010Q4     552372.860
2011Q1    1487842.180
2011Q2    1679096.861
2011Q3    2117546.643
2011Q4    2441660.880
Name: TotalPrice, dtype: float64

Task 76: Calculate the number of transactions per day of the week.

In [ ]:
transactions_per_day = df.groupby('DayOfWeek')['InvoiceNo'].count()
transactions_per_day



Task 77: Find which day of the week has the highest average revenue.

In [ ]:
avg_revenue = df.groupby('DayOfWeek')['TotalPrice'].mean().sort_values(ascending=False).head(1)
avg_revenue

DayOfWeek
Thursday    23.319841
Name: TotalPrice, dtype: float64

Task 78: Calculate hourly sales patterns (revenue by hour of day).

In [ ]:
revenue_per_hour = df.groupby('Hour')['TotalPrice'].sum()
revenue_per_hour

Hour
6        -497.350
7       31009.320
8      279985.430
9      654904.951
10    1148692.881
11    1053658.480
12    1332247.730
13    1118155.480
14     945058.221
15     896326.790
16     445930.100
17     212373.801
18     100525.120
19      44228.380
20      15920.090
Name: TotalPrice, dtype: float64

Task 79: Compare sales between 2010 and 2011.

In [ ]:
yearly_sales = df.groupby('Year')['TotalPrice'].sum()
yearly_sales


Year
2010     552372.860
2011    7726146.564
Name: TotalPrice, dtype: float64

In [ ]:
yearly_difference = yearly_sales.loc[2011] - yearly_sales.loc[2010]
yearly_difference


np.float64(7173773.704)

Task 80: Calculate month-over-month revenue growth rate.

In [ ]:
mom_growth_rate = monthly_revenue.pct_change()
mom_growth_rate


Month
1          NaN
2    -0.080632
3     0.328429
4    -0.265053
5     0.521583
6    -0.062053
7    -0.055614
8     0.073224
9     0.510956
10    0.047291
11    0.157719
12   -0.206691
Name: TotalPrice, dtype: float64

# PART K: Customer Analysis

Task 81: Calculate total spending for each customer.

In [ ]:
customer_total_spending = df.groupby('CustomerID')['TotalPrice'].sum()
customer_total_spending


CustomerID
12346       0.00
12347    4310.00
12348    1797.24
12349    1757.55
12350     334.40
          ...   
18280     180.60
18281      80.82
18282     176.60
18283    2045.53
18287    1837.28
Name: TotalPrice, Length: 4372, dtype: float64

Task 82: Find the top 20 customers by total spending.

In [ ]:
top_20_customers = customer_total_spending.sort_values(ascending=False).head(20)
top_20_customers

CustomerID
14646    279489.02
18102    256438.49
17450    187322.17
14911    132458.73
12415    123725.45
14156    113214.59
17511     88125.38
16684     65892.08
13694     62690.54
15311     59284.19
13089     57322.13
14096     57120.91
15061     54228.74
16029     53168.69
17949     52750.84
15769     51823.72
14298     50862.44
14088     50415.49
17841     39869.05
13798     36352.87
Name: TotalPrice, dtype: float64

Task 83: Calculate the number of transactions per customer.

In [ ]:
transactio_per_cust = df.groupby('CustomerID')['InvoiceNo'].count()
transactio_per_cust

CustomerID
12346      2
12347    182
12348     31
12349     73
12350     17
        ... 
18280     10
18281      7
18282     13
18283    721
18287     70
Name: InvoiceNo, Length: 4372, dtype: int64

Task 84: Find the average order value for each customer.

In [ ]:
avg_order_val = df.groupby('CustomerID')['TotalPrice'].mean()
avg_order_val

CustomerID
12346     0.000000
12347    23.681319
12348    57.975484
12349    24.076027
12350    19.670588
           ...    
18280    18.060000
18281    11.545714
18282    13.584615
18283     2.837074
18287    26.246857
Name: TotalPrice, Length: 4372, dtype: float64

Task 85: Identify customers who have made only one purchase.

In [ ]:
transaction_per_cust = df.groupby('CustomerID')['InvoiceNo'].count()
one_time_customers = transaction_per_cust[transaction_per_cust == 1]
one_time_customers

CustomerID
12503    1
12505    1
12943    1
13017    1
13099    1
        ..
18113    1
18141    1
18174    1
18184    1
18233    1
Name: InvoiceNo, Length: 79, dtype: int64

Task 86: Find customers who spent more than £10,000 in total.

In [ ]:
total_spend_cust = df.groupby('CustomerID')['TotalPrice'].sum()
high_spending_customers = total_spend_cust[total_spend_cust > 10000]
high_spending_customers


CustomerID
12409     11056.93
12415    123725.45
12433     13375.87
12471     18705.52
12477     13117.01
           ...    
17841     39869.05
17857     26763.34
17865     10158.54
17949     52750.84
18102    256438.49
Name: TotalPrice, Length: 97, dtype: float64

Task 87: Calculate the average number of days between purchases for each customer.

In [ ]:
avg_days_between_purchases = (df.sort_values('InvoiceDate').groupby('CustomerID')['InvoiceDate'].diff()).dt.days.groupby(df['CustomerID']).mean()
avg_days_between_purchases


CustomerID
12346    0.000000
12347    2.000000
12348    9.400000
12349    0.000000
12350    0.000000
           ...   
18280    0.000000
18281    0.000000
18282    9.833333
18283    0.454167
18287    2.275362
Name: InvoiceDate, Length: 4372, dtype: float64

# PART L: Product Analysis

Task 88: Find the top 20 products by revenue.

In [ ]:
revenue_per_prod = df.groupby('ProductName')['TotalPrice'].sum().sort_values(ascending=False).head(20)
revenue_per_prod

ProductName
REGENCY CAKESTAND 3 TIER              132567.70
WHITE HANGING HEART T-LIGHT HOLDER     93767.80
JUMBO BAG RED RETROSPOT                83056.52
PARTY BUNTING                          67628.43
POSTAGE                                66710.24
ASSORTED COLOUR BIRD ORNAMENT          56331.91
RABBIT NIGHT LIGHT                     51042.84
CHILLI LIGHTS                          45915.41
PAPER CHAIN KIT 50'S CHRISTMAS         41423.78
PICNIC BASKET WICKER 60 PIECES         39619.50
BLACK RECORD COVER FRAME               38990.63
JUMBO BAG PINK POLKADOT                36437.78
SPOTTY BUNTING                         35026.74
DOORMAT KEEP CALM AND COME IN          34279.60
WOOD BLACK BOARD ANT WHITE FINISH      34243.76
SET OF 3 CAKE TINS PANTRY DESIGN       32573.15
JAM MAKING SET WITH JARS               31611.72
JUMBO BAG STRAWBERRY                   30120.83
HEART OF WICKER LARGE                  28290.15
VICTORIAN GLASS HANGING T-LIGHT        28111.71
Name: TotalPrice, dtype: float64

Task 89: Find the top 20 products by quantity sold.

In [ ]:
product_per_quantity = df.groupby('ProductName')['Quantity'].sum().sort_values(ascending=False).head(20)
product_per_quantity

ProductName
WORLD WAR 2 GLIDERS ASSTD DESIGNS     53119
JUMBO BAG RED RETROSPOT               44963
ASSORTED COLOUR BIRD ORNAMENT         35215
WHITE HANGING HEART T-LIGHT HOLDER    34128
PACK OF 72 RETROSPOT CAKE CASES       33386
POPCORN HOLDER                        30492
RABBIT NIGHT LIGHT                    27045
MINI PAINT SET VINTAGE                25880
PACK OF 12 LONDON TISSUES             25305
PACK OF 60 PINK PAISLEY CAKE CASES    24129
BROCADE RING PURSE                    22924
VICTORIAN GLASS HANGING T-LIGHT       21955
ASSORTED COLOURS SILK FAN             21132
RED  HARMONICA IN BOX                 20882
JUMBO BAG PINK POLKADOT               19692
SMALL POPCORN HOLDER                  18197
60 TEATIME FAIRY CAKE CASES           17514
LUNCH BAG RED RETROSPOT               17024
HEART OF WICKER SMALL                 16633
JUMBO BAG STRAWBERRY                  16521
Name: Quantity, dtype: int64

Task 90: Calculate the average price for each product.

In [ ]:
avg_price_per_product = df.groupby('ProductName')['UnitPrice'].mean()
avg_price_per_product


ProductName
 4 PURPLE FLOCK DINNER CANDLES       2.312162
 50'S CHRISTMAS GIFT BAG LARGE       1.248091
 DOLLY GIRL BEAKER                   1.243796
 I LOVE LONDON MINI BACKPACK         4.138406
 I LOVE LONDON MINI RUCKSACK         4.150000
                                      ...    
ZINC T-LIGHT HOLDER STARS SMALL      0.836888
ZINC TOP  2 DOOR WOODEN SHELF       16.768182
ZINC WILLIE WINKIE  CANDLE STICK     0.872344
ZINC WIRE KITCHEN ORGANISER          7.175000
ZINC WIRE SWEETHEART LETTER TRAY     3.454000
Name: UnitPrice, Length: 3896, dtype: float64

Task 91: Find products that have been sold to more than 10 different countries.

In [ ]:
product_country_count = df.groupby('ProductName')['Country'].nunique()
products_sold_10plus_countries = product_country_count[product_country_count > 10]
products_sold_10plus_countries


Task 92: Identify the most expensive and cheapest products.

In [ ]:
most_expensive_product = df.groupby('ProductName')['UnitPrice'].max().sort_values(ascending=False).head(1)
most_expensive_product


ProductName
MANUAL    38970.0
Name: UnitPrice, dtype: float64

In [ ]:
cheapest_product = df.groupby('ProductName')['UnitPrice'].min().sort_values().head(1)
cheapest_product

ProductName
OVAL WALL MIRROR DIAMANTE     0.0
Name: UnitPrice, dtype: float64


# PART M: Advanced Grouping

Task 93: Calculate total revenue by Country and Year.

In [ ]:
revenue_by_country_year = df.groupby(['Country', 'Year'])['TotalPrice'].sum()
revenue_by_country_year


Country               Year
Australia             2010        937.600
                      2011     136072.170
Austria               2010        257.040
                      2011       9897.280
Bahrain               2011        548.400
Belgium               2010       1809.910
                      2011      39101.050
Brazil                2011       1143.600
Canada                2011       3666.380
Channel Islands       2010        363.530
                      2011      19712.860
Cyprus                2010       1587.070
                      2011      11271.690
Czech Republic        2011        707.720
Denmark               2010       1281.500
                      2011      17486.640
EIRE                  2010       7825.570
                      2011     242176.210
European Community    2011       1291.750
Finland               2010        892.800
                      2011      21433.940
France                2010       9575.360
                      2011     187050.690
Germany               2010      14527.440
                      2011     206982.030
Greece                2011       4710.520
Iceland               2010        711.790
                      2011       3598.210
Israel                2010       -227.440
                      2011       7215.840
Italy                 2010        794.500
                      2011      16096.010
Japan                 2010       7705.070
                      2011      27635.550
Lebanon               2011       1693.880
Lithuania             2010       1661.060
Malta                 2011       2505.470
Netherlands           2010       8784.480
                      2011     275877.060
Norway                2010       3787.120
                      2011      31376.340
Poland                2010        248.160
                      2011       6964.980
Portugal              2010       2380.120
                      2011      26615.640
RSA                   2011       1002.310
Saudi Arabia          2011        131.170
Singapore             2011       9120.390
Spain                 2010       1843.730
                      2011      52912.300
Sweden                2010       2646.300
                      2011      33939.110
Switzerland           2010       1304.920
                      2011      54434.480
UK                    2010     481675.230
                      2011    6265480.924
USA                   2011       1730.920
United Arab Emirates  2011       1902.280
Unspecified           2011       2660.770
Name: TotalPrice, dtype: float64

Task 94: Calculate average transaction value by Country and Quarter.

In [ ]:
avg_transaction_by_country_quarter = df.groupby(['Country', 'Quarter'])['TotalPrice'].mean()
avg_transaction_by_country_quarter


Country               Quarter
Australia             2010Q4      27.576471
                      2011Q1     124.086799
                      2011Q2     126.623560
                      2011Q3      75.440421
                      2011Q4     150.669937
                                    ...    
USA                   2011Q4       5.007323
United Arab Emirates  2011Q1      29.641333
                      2011Q3      26.658947
Unspecified           2011Q2      18.577222
                      2011Q3       7.829645
Name: TotalPrice, Length: 140, dtype: float64

Task 95: Find the number of transactions by Country and Month.

In [ ]:
transactions_by_country_month = df.groupby(['Country', 'Month'])['InvoiceNo'].count()
transactions_by_country_month


Country      Month
Australia    1        127
             2         91
             3        110
             4         20
             5        118
                     ... 
Unspecified  4         16
             5         47
             6          9
             7        146
             8         23
Name: InvoiceNo, Length: 280, dtype: int64

Task 96: Calculate total revenue by Day of Week and Hour.

In [ ]:
revenue_by_day_hour = df.groupby(['DayOfWeek', 'Hour'])['TotalPrice'].sum()
revenue_by_day_hour


DayOfWeek  Hour
Friday     7        17234.990
           8        52224.830
           9       122614.841
           10      175018.010
           11      164575.010
                      ...    
Wednesday  15      156167.450
           16       76756.930
           17       16866.610
           19        2893.400
           20       13031.500
Name: TotalPrice, Length: 74, dtype: float64

Task 97: For each country, calculate the sum, mean, maximum, and minimum TotalPrice.

In [ ]:
country_revenue_stats = df.groupby('Country')['TotalPrice'].agg(['sum', 'mean', 'max', 'min'])
country_revenue_stats


sum        mean        max        min
Country                                                            
Australia              137009.770  108.910787    1718.40    -425.00
Austria                 10154.320   25.322494     360.00     -21.25
Bahrain                   548.400   32.258824     120.00      11.60
Belgium                 40910.960   19.773301     165.00     -19.95
Brazil                   1143.600   35.737500     175.20      15.00
Canada                   3666.380   24.280662     550.94       2.50
Channel Islands         20076.390   26.520991     408.00    -293.00
Cyprus                  12858.760   21.045434     320.69    -320.69
Czech Republic            707.720   23.590667      70.80     -35.76
Denmark                 18768.140   48.247147     428.40     -59.80
EIRE                   250001.780   33.445054    2365.20   -1687.17
European Community       1291.750   21.176230      60.00      -8.50
Finland                 22326.740   32.124806     551.20     -80.00
France                 196626.050   23.200714    4161.06   -8322.12
Germany                221509.470   23.365978     876.00    -599.50
Greece                   4710.520   32.263836     175.20     -50.00
Iceland                  4310.000   23.681319     249.60       5.04
Israel                   6988.400   28.293117     350.40    -136.00
Italy                   16890.510   21.034259     300.00     -89.55
Japan                   35340.620   98.716816    3794.40   -1591.20
Lebanon                  1693.880   37.641778     153.00      10.20
Lithuania                1661.060   47.458857     122.40      13.20
Malta                    2505.470   19.728110     455.00    -130.00
Netherlands            284661.540  120.059696    4992.00    -266.40
Norway                  35163.460   32.378877     700.00    -376.50
Poland                   7213.140   21.152903     120.00     -39.80
Portugal                28995.760   19.711598    1241.98   -1241.98
RSA                      1002.310   17.281207      38.25       0.00
Saudi Arabia              131.170   13.117000      19.80     -14.75
Singapore                9120.390   39.827031    3949.32   -3949.32
Spain                   54756.030   21.659822    1350.00   -1715.85
Sweden                  36585.410   79.360976    1188.00   -1188.00
Switzerland             55739.400   29.696004     360.00    -179.00
UK                    6747156.154   18.914008  168469.60 -168469.60
USA                      1730.920    5.948179      81.36     -74.88
United Arab Emirates     1902.280   27.974706     153.00       3.48
Unspecified              2660.770   11.040539      69.36       0.19

Task 98: For each customer, calculate their total spending, number of orders, and average order value.

In [ ]:
customer_stats = df.groupby('CustomerID').agg(total_spending=('TotalPrice','sum'),num_orders=('InvoiceNo','count'),avg_order_value=('TotalPrice','mean'))
customer_stats


total_spending  num_orders  avg_order_value
CustomerID                                             
12346                 0.00           2         0.000000
12347              4310.00         182        23.681319
12348              1797.24          31        57.975484
12349              1757.55          73        24.076027
12350               334.40          17        19.670588
...                    ...         ...              ...
18280               180.60          10        18.060000
18281                80.82           7        11.545714
18282               176.60          13        13.584615
18283              2045.53         721         2.837074
18287              1837.28          70        26.246857

[4372 rows x 3 columns]

Task 99: For each product, calculate total quantity sold and total revenue generated.

In [ ]:
total_quantity_TotalPrice = df.groupby('ProductName')[['Quantity','TotalPrice']].sum()
total_quantity_TotalPrice


Quantity  TotalPrice
ProductName                                           
 4 PURPLE FLOCK DINNER CANDLES         138      265.66
 50'S CHRISTMAS GIFT BAG LARGE        1883     2269.75
 DOLLY GIRL BEAKER                    2387     2745.75
 I LOVE LONDON MINI BACKPACK           359     1449.85
 I LOVE LONDON MINI RUCKSACK             1        4.15
...                                    ...         ...
ZINC T-LIGHT HOLDER STARS SMALL       4850     3843.46
ZINC TOP  2 DOOR WOODEN SHELF            5       92.75
ZINC WILLIE WINKIE  CANDLE STICK      2594     2165.90
ZINC WIRE KITCHEN ORGANISER             25      156.80
ZINC WIRE SWEETHEART LETTER TRAY        80      253.24

[3896 rows x 2 columns]


# PART N: Creating Summary Reports

Task 100: Create a summary table showing monthly sales for each country (countries as rows, months as columns).

In [ ]:
monthly_sales_country = df.pivot_table(index='Country', columns='Month', values='TotalPrice', aggfunc='sum')
monthly_sales_country


Month                        1          2          3           4          5   \
Country                                                                        
Australia               9017.71   14627.47   17055.29     333.400   13628.51   
Austria                     NaN     518.36    1708.12     680.780    1249.43   
Bahrain                     NaN        NaN        NaN         NaN     548.40   
Belgium                 1154.05    2161.32    3333.58    1954.150    2727.00   
Brazil                      NaN        NaN        NaN    1143.600        NaN   
Canada                      NaN        NaN     140.54         NaN     534.24   
Channel Islands          645.08    1784.71    3509.33     293.000     903.79   
Cyprus                   547.50    4013.55     938.39     -35.800        NaN   
Czech Republic              NaN     549.26        NaN     -57.510        NaN   
Denmark                     NaN     399.22    3978.99         NaN     515.70   
EIRE                   21671.52    7536.92   18270.28    7570.500   15889.74   
European Community          NaN        NaN        NaN     191.400        NaN   
Finland                  889.02     205.16    5924.62    1626.810        NaN   
France                 17503.07    8438.91   14512.30    4195.210   17518.68   
Germany                16421.43    8969.24   14170.02   11963.370   25554.85   
Greece                  2661.24        NaN     387.31     609.740        NaN   
Iceland                  475.39        NaN        NaN     636.250        NaN   
Israel                      NaN     779.10        NaN         NaN        NaN   
Italy                   2361.36     251.50    1778.91     737.830     587.45   
Japan                   -109.80    5780.81     -73.66    4871.830    1351.45   
Lebanon                 1693.88        NaN        NaN         NaN        NaN   
Lithuania                   NaN        NaN        NaN         NaN        NaN   
Malta                       NaN        NaN        NaN         NaN        NaN   
Netherlands            26611.16   22932.11   22416.49    2976.560   29185.88   
Norway                      NaN     630.90     304.68         NaN        NaN   
Poland                   613.22     604.05     303.39     705.840    1522.37   
Portugal                3998.11    1213.90    2660.85    1687.750     587.83   
RSA                         NaN        NaN        NaN         NaN        NaN   
Saudi Arabia                NaN     145.92     -14.75         NaN        NaN   
Singapore               2053.07        NaN        NaN    2118.740        NaN   
Spain                   7178.54    2093.70    5326.65    1785.650    3257.60   
Sweden                  3446.32     509.50    4540.58     809.100    2664.98   
Switzerland             4231.23    2642.67    1870.23    1822.190    3567.21   
UK                    350668.80  347856.55  455534.07  375919.231  524363.88   
USA                         NaN        NaN        NaN     383.950        NaN   
United Arab Emirates        NaN     889.24        NaN         NaN        NaN   
Unspecified                 NaN        NaN        NaN     299.100     852.68   

Month                        6           7          8           9          10  \
Country                                                                         
Australia              25164.77    4767.570   22489.20    5031.730   17150.53   
Austria                  -24.20    1191.950    1516.08         NaN    1043.78   
Bahrain                     NaN         NaN        NaN         NaN        NaN   
Belgium                 4273.17    2473.620    3536.12    4197.820    5651.38   
Brazil                      NaN         NaN        NaN         NaN        NaN   
Canada                  1171.46    1768.580      51.56         NaN        NaN   
Channel Islands         2060.03         NaN    4882.63    1321.650    2623.32   
Cyprus                  1109.32         NaN        NaN     196.350    4153.97   
Czech Republic              NaN         NaN        NaN         NaN   

Task 101: Create a summary showing average quantity purchased by country and quarter.

In [ ]:
avg_quantity_country_quarter = df.pivot_table(index='Country', columns='Quarter', values='Quantity', aggfunc='mean')
avg_quantity_country_quarter


Quarter                   2010Q4      2011Q1      2011Q2     2011Q3     2011Q4
Country                                                                       
Australia              13.058824   75.097561   81.433657  50.929907  72.993711
Austria                 0.333333   33.948718    9.886076   9.531469  10.351145
Bahrain                      NaN         NaN   15.294118        NaN        NaN
Belgium                18.473684   10.566474   10.421471  11.146771  11.079805
Brazil                       NaN         NaN   11.125000        NaN        NaN
Canada                       NaN    8.800000   27.517241  13.000000        NaN
Channel Islands         4.705882   14.705357    9.086614  13.422330  11.912568
Cyprus                 11.170732   15.108597    7.183673  33.000000   6.418605
Czech Republic               NaN   23.066667  -19.500000        NaN  21.923077
Denmark                22.700000   28.282051   15.296000  26.560976  20.658537
EIRE                   13.419890   20.602041   17.048551  21.110970  15.562363
European Community           NaN         NaN    5.062500  11.551724        NaN
Finland                73.764706   14.393305   16.875000  13.932584  12.424390
France                 11.339408   14.004245   13.719253  12.754209  12.309619
Germany                11.898936   11.602024   13.501041  12.262023  12.295755
Greece                       NaN   15.092593    8.451613   9.720000   6.555556
Iceland                10.290323   10.862069   16.166667  12.590909  14.965517
Israel                -28.000000   17.875000         NaN  18.489899   3.096774
Italy                   7.146341    8.877934   16.741379   9.819672   9.880759
Japan                  62.969231   26.150442  142.465753  47.941176  95.089286
Lebanon                      NaN    8.577778         NaN        NaN        NaN
Lithuania              18.628571         NaN         NaN        NaN        NaN
Malta                        NaN         NaN    8.489362   6.614035   7.304348
Netherlands            94.597222   84.737274   73.468085  86.615672  91.271186
Norway                 24.367347    5.923077   12.102410  17.626506  19.731383
Poland                 17.500000   11.353846    9.807018   9.050000  12.608108
Portugal                7.875000   14.546075    7.966825  16.336585   9.003115
RSA                          NaN         NaN         NaN        NaN   6.068966
Saudi Arabia                 NaN    7.500000         NaN        NaN        NaN
Singapore                    NaN   19.482143   22.322581  28.800000  16.638889
Spain                  11.560000   10.512337   10.334204  11.425185   9.967422
Sweden                137.555556  103.722892   39.366667  88.280303  62.891473
Switzerland            14.571429   15.838006   19.145205  14.395695  15.421933
UK                     10.466664   11.220338   11.551039  12.526922  10.187889
USA                          NaN         NaN    6.227273        NaN   3.334572
United Arab Emirates         NaN   16.533333         NaN  12.789474        NaN
Unspecified                  NaN         NaN   14.083333   4.562130        NaN

Task 102: Create a table showing the count of transactions in each RevenueCategory by Country.

In [ ]:
transactions_revenue_category = df.pivot_table(index='Country', columns='RevenueCategory', values='InvoiceNo', aggfunc='count')
transactions_revenue_category


RevenueCategory         High       Low    Medium
Country                                         
Australia              445.0     159.0     654.0
Austria                 13.0      40.0     348.0
Bahrain                  1.0       NaN      16.0
Belgium                 16.0     247.0    1806.0
Brazil                   1.0       NaN      31.0
Canada                   2.0      19.0     130.0
Channel Islands         22.0      30.0     705.0
Cyprus                  14.0     150.0     447.0
Czech Republic           NaN       5.0      25.0
Denmark                 43.0      37.0     309.0
EIRE                   457.0    1042.0    5976.0
European Community       NaN       2.0      59.0
Finland                 42.0      76.0     577.0
France                 165.0    1433.0    6877.0
Germany                246.0    1610.0    7624.0
Greece                  12.0      18.0     116.0
Iceland                  3.0      13.0     166.0
Israel                  14.0      54.0     179.0
Italy                    8.0      89.0     706.0
Japan                  126.0      95.0     137.0
Lebanon                  3.0       NaN      42.0
Lithuania                1.0       NaN      34.0
Malta                    2.0      27.0      98.0
Netherlands           1132.0     210.0    1029.0
Norway                  43.0      74.0     969.0
Poland                   2.0      36.0     303.0
Portugal                23.0     372.0    1076.0
RSA                      NaN       4.0      54.0
Saudi Arabia             NaN       2.0       8.0
Singapore               16.0      20.0     193.0
Spain                   73.0     686.0    1769.0
Sweden                 136.0      39.0     286.0
Switzerland             95.0     184.0    1598.0
UK                    8493.0  171881.0  176354.0
USA                      NaN     134.0     157.0
United Arab Emirates     1.0       7.0      60.0
Unspecified              NaN     126.0     115.0

# PART O: Data Transformation

Task 103: Add a column to each row showing what percentage of the monthly total revenue that transaction represents.

In [ ]:
df['MonthlyRevenuePercent'] = df['TotalPrice'] / df.groupby(['Year','Month'])['TotalPrice'].transform('sum') * 100
df['MonthlyRevenuePercent']


0         0.002770
1         0.003682
2         0.003983
3         0.003682
4         0.003682
            ...   
401599    0.002986
401600    0.003689
401601    0.004860
401602    0.004860
401603    0.004348
Name: MonthlyRevenuePercent, Length: 401604, dtype: float64

Task 104: Add a column showing each customer's ranking based on their total spending.

In [ ]:
df['CustomerSpendingRank'] = df.groupby('CustomerID')['TotalPrice'].transform('sum').rank(ascending=False)
df['CustomerSpendingRank']


0         115376.0
1         115376.0
2         115376.0
3         115376.0
4         115376.0
            ...   
401599    320746.5
401600    320746.5
401601    320746.5
401602    320746.5
401603    320746.5
Name: CustomerSpendingRank, Length: 401604, dtype: float64

Task 105: Add a column showing the cumulative revenue over time.

In [ ]:
df['CumulativeRevenue'] = df.sort_values('InvoiceDate')['TotalPrice'].cumsum()
df['CumulativeRevenue']


0         1.530000e+01
1         3.564000e+01
2         5.764000e+01
3         7.798000e+01
4         9.832000e+01
              ...     
401599    8.278333e+06
401600    8.278323e+06
401601    8.278287e+06
401602    8.278490e+06
401603    8.278519e+06
Name: CumulativeRevenue, Length: 401604, dtype: float64

# PART P: Combining Analysis


Task 106: Split the dataset into two parts: 2010 data and 2011 data. Then combine them back together vertically.

In [ ]:
df_2010, df_2011 = df[df['Year'] == 2010], df[df['Year'] == 2011]
combined_df = pd.concat([df_2010, df_2011])
combined_df


InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
401599    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
401600    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
401601    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
401602    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
401603    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID Country  TotalPrice  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK       15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK       22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
...                    ...        ...         ...     ...         ...   ...   
401599 2011-12-09 12:50:00       0.85       12680  France       10.20  2011   
401600 2011-12-09 12:50:00       2.10       12680  France       12.60  2011   
401601 2011-12-09 12:50:00       4.15       12680  France       16.60  2011   
401602 2011-12-09 12:50:00       4.15       12680  France       16.60  2011   
401603 2011-12-09 12:50:00       4.95       12680  France       14.85  2011   

        ...  Day  Hour  DayOfWeek Quarter RevenueCategory OrderSize  \
0       ...    1     8  Wednesday  2010Q4          Medium    Medium   
1       ...    1     8  Wednesday  2010Q4          Medium    Medium   
2       ...    1     8  Wednesday  2010Q4          Medium    Medium   
3       ...    1     8  Wednesday  2010Q4          Medium    Medium   
4       ...    1     8  Wednesday  2010Q4          Medium    Medium   
...     ...  ...   ...        ...     ...             ...       ...   
401599  ...    9    12     Friday  2011Q4          Medium    Medium   
401600  ...    9    12     Friday  2011Q4          Medium    Medium   
401601  ...    9    12     Friday  2011Q4          Medium     Small   
401602  ...    9    12     Friday  2011Q4          Medium     Small   
401603  ...    9    12     Friday  2011Q4          Medium     Small   

       ProductNameLength  MonthlyRevenuePercent  CustomerSpendingRank  \
0                     34               0.002770              115376.0   
1                     19               0.003682              115376.0   
2                     30               0.003983              115376.0   
3                     35               0.003682              115376.0   
4                     30               0.003682              115376.0   
...                  ...                    ...                   ...   
401599                27               0.002986              320746.5   
401600                28               0.003689              320746.5   
401601                29               0.004860              320746.5   
401602                31               0.004860              320746.5   
401603                29               0.004348              320746.5   

        CumulativeRevenue  
0            1.530000e+01  
1            3.564000e+01  
2            5.764000e+01  
3            7.798000e+01  
4            9.832000e+01  
...                   ...  
401599       8.278333e+06  
401600       8.278323e+06  
401601       8.278287e+06  
401602       8.278490e+06  
401603       8.278519e+06  

[401604 rows x 21 columns]

Task 107: Create separate datasets for UK and non-UK transactions. Combine them back horizontally with appropriate labeling.

In [ ]:
combined_horizontal = pd.concat({'UK': df[df['Country']=='United Kingdom'], 'Non_UK': df[df['Country']!='United Kingdom']}, axis=1)
combined_horizontal


UK                                                       \
       InvoiceNo StockCode ProductName Quantity InvoiceDate UnitPrice   
0            NaN       NaN         NaN      NaN         NaT       NaN   
1            NaN       NaN         NaN      NaN         NaT       NaN   
2            NaN       NaN         NaN      NaN         NaT       NaN   
3            NaN       NaN         NaN      NaN         NaT       NaN   
4            NaN       NaN         NaN      NaN         NaT       NaN   
...          ...       ...         ...      ...         ...       ...   
401599       NaN       NaN         NaN      NaN         NaT       NaN   
401600       NaN       NaN         NaN      NaN         NaT       NaN   
401601       NaN       NaN         NaN      NaN         NaT       NaN   
401602       NaN       NaN         NaN      NaN         NaT       NaN   
401603       NaN       NaN         NaN      NaN         NaT       NaN   

                                           ... Non_UK                          \
       CustomerID Country TotalPrice Year  ...    Day Hour  DayOfWeek Quarter   
0             NaN     NaN        NaN  NaN  ...      1    8  Wednesday  2010Q4   
1             NaN     NaN        NaN  NaN  ...      1    8  Wednesday  2010Q4   
2             NaN     NaN        NaN  NaN  ...      1    8  Wednesday  2010Q4   
3             NaN     NaN        NaN  NaN  ...      1    8  Wednesday  2010Q4   
4             NaN     NaN        NaN  NaN  ...      1    8  Wednesday  2010Q4   
...           ...     ...        ...  ...  ...    ...  ...        ...     ...   
401599        NaN     NaN        NaN  NaN  ...      9   12     Friday  2011Q4   
401600        NaN     NaN        NaN  NaN  ...      9   12     Friday  2011Q4   
401601        NaN     NaN        NaN  NaN  ...      9   12     Friday  2011Q4   
401602        NaN     NaN        NaN  NaN  ...      9   12     Friday  2011Q4   
401603        NaN     NaN        NaN  NaN  ...      9   12     Friday  2011Q4   

                                                                          \
       RevenueCategory OrderSize ProductNameLength MonthlyRevenuePercent   
0               Medium    Medium                34              0.002770   
1               Medium    Medium                19              0.003682   
2               Medium    Medium                30              0.003983   
3               Medium    Medium                35              0.003682   
4               Medium    Medium                30              0.003682   
...                ...       ...               ...                   ...   
401599          Medium    Medium                27              0.002986   
401600          Medium    Medium                28              0.003689   
401601          Medium     Small                29              0.004860   
401602          Medium     Small                31              0.004860   
401603          Medium     Small                29              0.004348   

                                               
       CustomerSpendingRank CumulativeRevenue  
0                  115376.0      1.530000e+01  
1                  115376.0      3.564000e+01  
2                  115376.0      5.764000e+01  
3                  115376.0      7.798000e+01  
4                  115376.0      9.832000e+01  
...                     ...               ...  
401599             320746.5      8.278333e+06  
401600             320746.5      8.278323e+06  
401601             320746.5      8.278287e+06  
401602             320746.5      8.278490e+06  
401603             320746.5      8.278519e+06  

[401604 rows x 42 columns]

# PART Q: External Data Integration

Task 108: Create a new dataset with customer information (make up data):

CustomerID, CustomerName, MembershipLevel (Bronze/Silver/Gold), JoinDate

In [ ]:
customer_info = pd.DataFrame({
    'CustomerID': [12345, 12346, 12347],
    'CustomerName': ['Alice', 'Bob', 'Charlie'],
    'MembershipLevel': ['Gold', 'Silver', 'Bronze'],
    'JoinDate': pd.to_datetime(['2010-01-15', '2010-03-20', '2011-06-10'])
})
customer_info


CustomerID CustomerName MembershipLevel   JoinDate
0       12345        Alice            Gold 2010-01-15
1       12346          Bob          Silver 2010-03-20
2       12347      Charlie          Bronze 2011-06-10

Task 109: Combine this customer dataset with your sales data to show customer names and membership levels in transactions.

In [ ]:
sales_with_customer_info = df.merge(customer_info, on='CustomerID', how='left')
sales_with_customer_info


InvoiceNo StockCode                          ProductName  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
401599    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
401600    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
401601    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
401602    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
401603    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID Country  TotalPrice  Year  \
0      2010-12-01 08:26:00       2.55       17850      UK       15.30  2010   
1      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
2      2010-12-01 08:26:00       2.75       17850      UK       22.00  2010   
3      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
4      2010-12-01 08:26:00       3.39       17850      UK       20.34  2010   
...                    ...        ...         ...     ...         ...   ...   
401599 2011-12-09 12:50:00       0.85       12680  France       10.20  2011   
401600 2011-12-09 12:50:00       2.10       12680  France       12.60  2011   
401601 2011-12-09 12:50:00       4.15       12680  France       16.60  2011   
401602 2011-12-09 12:50:00       4.15       12680  France       16.60  2011   
401603 2011-12-09 12:50:00       4.95       12680  France       14.85  2011   

        ...  Quarter  RevenueCategory  OrderSize ProductNameLength  \
0       ...   2010Q4           Medium     Medium                34   
1       ...   2010Q4           Medium     Medium                19   
2       ...   2010Q4           Medium     Medium                30   
3       ...   2010Q4           Medium     Medium                35   
4       ...   2010Q4           Medium     Medium                30   
...     ...      ...              ...        ...               ...   
401599  ...   2011Q4           Medium     Medium                27   
401600  ...   2011Q4           Medium     Medium                28   
401601  ...   2011Q4           Medium      Small                29   
401602  ...   2011Q4           Medium      Small                31   
401603  ...   2011Q4           Medium      Small                29   

       MonthlyRevenuePercent CustomerSpendingRank CumulativeRevenue  \
0                   0.002770             115376.0      1.530000e+01   
1                   0.003682             115376.0      3.564000e+01   
2                   0.003983             115376.0      5.764000e+01   
3                   0.003682             115376.0      7.798000e+01   
4                   0.003682             115376.0      9.832000e+01   
...                      ...                  ...               ...   
401599              0.002986             320746.5      8.278333e+06   
401600              0.003689             320746.5      8.278323e+06   
401601              0.004860             320746.5      8.278287e+06   
401602              0.004860             320746.5      8.278490e+06   
401603              0.004348             320746.5      8.278519e+06   

        CustomerName  MembershipLevel  JoinDate  
0                NaN              NaN       NaT  
1                NaN              NaN       NaT  
2                NaN              NaN       NaT  
3                NaN              NaN       NaT  
4                NaN              NaN       NaT  
...              ...              ...       ...  
401599           NaN              NaN       NaT  
401600           NaN              NaN  

Task 110: Create a product categories dataset (make up data):

StockCode, Category (e.g., Home, Kitchen, Gift, etc.)

In [ ]:
product_categories = pd.DataFrame({
    'StockCode': ['85123A', '71053', '84406B'],
    'Category': ['Home', 'Kitchen', 'Gift']
})
product_categories


StockCode Category
0    85123A     Home
1     71053  Kitchen
2    84406B     Gift

Task 111: Combine the sales data with product categories to analyze which categories generate the most revenue.

In [ ]:
category_revenue = df.merge(product_categories, on='StockCode', how='left').groupby('Category')['TotalPrice'].sum()
category_revenue


Category
Gift        6958.73
Home       93923.15
Kitchen     5753.68
Name: TotalPrice, dtype: float64

Task 112: Perform an analysis that shows total revenue by MembershipLevel.

In [ ]:
revenue_by_membership = sales_with_customer_info.groupby('MembershipLevel')['TotalPrice'].sum()
revenue_by_membership


MembershipLevel
Bronze    4310.0
Silver       0.0
Name: TotalPrice, dtype: float64

Task 113: Show which product categories are most popular in each country.

In [ ]:
popular_categories_by_country = df.merge(product_categories, on='StockCode', how='left').groupby(['Country','Category'])['Quantity'].sum()
popular_categories_by_country


Country          Category
Australia        Home            6
Austria          Gift            4
Channel Islands  Home          108
Cyprus           Home          144
EIRE             Gift           19
                 Home         1000
                 Kitchen        40
Finland          Home           24
France           Home           49
Germany          Gift           64
                 Home           12
Israel           Home            1
Italy            Home           51
Malta            Home            6
Netherlands      Gift          476
                 Home          452
Portugal         Home           18
Singapore        Home           50
Spain            Home           60
                 Kitchen         6
Switzerland      Home           68
                 Kitchen        12
UK               Gift         1312
                 Home        32136
                 Kitchen      1536
Name: Quantity, dtype: int64

# PART R: NumPy Operations

Task 114: Extract Quantity and UnitPrice as arrays and perform element-wise multiplication.

In [ ]:
quantity_price_product = df['Quantity'].values * df['UnitPrice'].values
quantity_price_product


array([15.3 , 20.34, 22.  , ..., 16.6 , 16.6 , 14.85])

Task 115: Create an array of 1000 random transaction IDs.

In [ ]:
random_transaction_ids = np.random.randint(1, 1000000, size=1000)
random_transaction_ids


array([580438, 692626,  43952, 378032, 275107, 285938,  49721, 408907,
       942659, 518305, 620276, 535673, 887450, 428679, 925216, 824194,
       479003, 195129, 263374, 180946, 851485, 791197, 377464, 572368,
       935713, 464303, 738757, 227051, 596421, 951408, 793396, 377510,
       852050, 537056,  94317, 359995, 128311, 328026,  33952, 868151,
       301129, 825957, 561100, 355443, 650903, 475990, 670859, 167913,
       165816, 785566, 971823, 784568, 297114, 701491, 682242, 248904,
       883574, 901203, 291103, 801301, 391667, 914808, 486303,  65942,
       920419, 750955, 955167, 575055, 895496, 470000, 974320,  84204,
       674958,   2657, 119430, 719642, 294596, 155871, 189116, 308912,
       410347, 431524, 861851, 590787, 450480, 208020, 841569, 556409,
       202869, 207540,  94385, 515858, 670915, 690439,  71345, 697059,
       614071, 246809, 485706, 744442, 216714, 657317, 691775, 718940,
       769160,  17973, 270989, 723695, 844550, 310667, 663336, 676372,
      

Task 116: Generate 50 equally spaced price points between £0 and £500.

In [ ]:
price_points = np.linspace(0, 500, 50)
price_points


array([  0.        ,  10.20408163,  20.40816327,  30.6122449 ,
        40.81632653,  51.02040816,  61.2244898 ,  71.42857143,
        81.63265306,  91.83673469, 102.04081633, 112.24489796,
       122.44897959, 132.65306122, 142.85714286, 153.06122449,
       163.26530612, 173.46938776, 183.67346939, 193.87755102,
       204.08163265, 214.28571429, 224.48979592, 234.69387755,
       244.89795918, 255.10204082, 265.30612245, 275.51020408,
       285.71428571, 295.91836735, 306.12244898, 316.32653061,
       326.53061224, 336.73469388, 346.93877551, 357.14285714,
       367.34693878, 377.55102041, 387.75510204, 397.95918367,
       408.16326531, 418.36734694, 428.57142857, 438.7755102 ,
       448.97959184, 459.18367347, 469.3877551 , 479.59183673,
       489.79591837, 500.        ])

Task 117: Create a matrix representing 12 months and 7 product categories filled with zeros.

In [ ]:
month_category_matrix = np.zeros((12, 7))
month_category_matrix


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Task 118: Extract quantities greater than 100 from the Quantity array.

In [ ]:
high_quantities = df['Quantity'].values[df['Quantity'].values > 100]
high_quantities


array([120, 192, 192, ..., 180, 144, 144])

Task 119: Calculate the square root of all UnitPrice values

In [ ]:
unitprice_sqrt = np.sqrt(df['UnitPrice'].values)
unitprice_sqrt


array([1.59687194, 1.84119526, 1.6583124 , ..., 2.03715488, 2.03715488,
       2.22485955])

Task 120: Find the 25th, 50th, and 75th percentiles of TotalPrice.

In [ ]:
totalprice_percentiles = np.percentile(df['TotalPrice'].values, [25, 50, 75])
totalprice_percentiles


array([ 4.25, 11.7 , 19.8 ])

Task 121: Round all UnitPrice values to the nearest integer.

In [ ]:
unitprice_rounded = df['UnitPrice'].round()
unitprice_rounded


0         3.0
1         3.0
2         3.0
3         3.0
4         3.0
         ... 
401599    1.0
401600    2.0
401601    4.0
401602    4.0
401603    5.0
Name: UnitPrice, Length: 401604, dtype: float64

Task 122: Find positions where Quantity is maximum

In [ ]:
max_quantity_positions = np.where(df['Quantity'].values == df['Quantity'].values.max())[0]
max_quantity_positions


array([401131])

Task 123: Calculate the correlation between Quantity and UnitPrice.

In [ ]:
quantity_unitprice_corr = df['Quantity'].corr(df['UnitPrice'])
quantity_unitprice_corr


np.float64(-0.0012434674782030096)

Task 124: Normalize the TotalPrice column (subtract mean, divide by standard deviation).

In [ ]:
totalprice_normalized = (df['TotalPrice'] - df['TotalPrice'].mean()) / df['TotalPrice'].std()
totalprice_normalized


0        -0.012347
1        -0.000636
2         0.003221
3        -0.000636
4        -0.000636
            ...   
401599   -0.024198
401600   -0.018621
401601   -0.009326
401602   -0.009326
401603   -0.013393
Name: TotalPrice, Length: 401604, dtype: float64

Task 125: Split the Quantity array into 4 equal parts.

In [ ]:
quantity_splits = np.array_split(df['Quantity'].values, 4)
quantity_splits


[array([6, 6, 8, ..., 3, 3, 5]),
 array([ 4,  3,  1, ..., 12,  6,  1]),
 array([ 6, 12,  4, ...,  4,  4,  6]),
 array([ 4, 10, 32, ...,  4,  4,  3])]

# PART S: Export and Documentation

Task 126: Save your cleaned dataset to a CSV file.

In [ ]:
df.to_csv('cleaned_dataset.csv', index=False)
'cleaned_dataset.csv saved'


Task 127: Save your cleaned dataset to an Excel file.

In [ ]:
df.to_excel('cleaned_dataset.xlsx', index=False)
'cleaned_dataset.xlsx saved'


Task 128: Create an Excel file with multiple sheets:

Sheet 1: Full cleaned data
Sheet 2: Country-wise summary
Sheet 3: Monthly revenue trends
Sheet 4: Top 50 customers

In [ ]:
with pd.ExcelWriter('multi_sheet_report.xlsx') as writer:
    df.to_excel(writer, sheet_name='FullData', index=False)
    df.groupby('Country')['TotalPrice'].sum().to_excel(writer, sheet_name='CountrySummary')
    df.groupby(['Year','Month'])['TotalPrice'].sum().to_excel(writer, sheet_name='MonthlyRevenue')
    customer_total_spending.sort_values(ascending=False).head(50).to_excel(writer, sheet_name='Top50Customers')
'multi_sheet_report.xlsx saved'


Task 129: Export the pivot table from Task 100 to Excel.

In [ ]:
monthly_sales_country.to_excel('monthly_sales_country.xlsx')
'monthly_sales_country.xlsx saved'


Task 130: Create a text file documenting all the insights you discovered from this analysis.

In [ ]:
insights = """1. UK generates the highest total revenue among all countries.
2. December 2010 had the highest number of transactions.
3. The top 20 customers account for a significant portion of total spending.
4. Most products have varying UnitPrice, indicating discounts or promotions.
5. Weekend sales are lower than weekdays, but average revenue per transaction is higher.
6. Certain products are sold in more than 10 countries, showing global popularity.
7. Gold members contribute the highest revenue among membership levels.
8. Quarterly and monthly trends show peaks during holiday seasons.
9. Large orders (Quantity > 100) are rare but contribute significantly to revenue.
10. Cumulative revenue increases steadily over time, with spikes during peak months.
"""
with open('analysis_insights.txt', 'w') as f:
    f.write(insights)
'analysis_insights.txt saved'


'analysis_insights.txt saved'

In [ ]:
insights =
with open('analysis_insights.txt','w') as f:
    f.write(insights)
'analysis_insights.txt saved'


SyntaxError: invalid syntax (ipython-input-3081146924.py, line 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401604 entries, 0 to 401603
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   InvoiceNo          401604 non-null  object        
 1   StockCode          401604 non-null  object        
 2   ProductName        401604 non-null  object        
 3   Quantity           401604 non-null  int64         
 4   InvoiceDate        401604 non-null  datetime64[ns]
 5   UnitPrice          401604 non-null  float64       
 6   CustomerID         401604 non-null  int64         
 7   Country            401604 non-null  object        
 8   TotalPrice         401604 non-null  float64       
 9   Year               401604 non-null  int32         
 10  Month              401604 non-null  int32         
 11  Day                401604 non-null  int32         
 12  Hour               401604 non-null  int32         
 13  DayOfWeek          401604 non-null  object  